apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/base/echo-server
  - ../../../apps/base/kubernetes-dashboard
  - ../../../apps/base/headlamp
  - ../../../apps/base/orion
  - ../../../apps/base/admin
  - ../../../apps/base/website
  - ../../../apps/base/openwebui
