---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secrets/ghcr-pull.yaml
  - ./secrets/authelia-config.yaml
  - ./secrets/authelia-extras.yaml
  - ./secrets/authelia-oidc-rsa.yaml
  - ./secrets/authelia-secrets.yaml
  - ./secrets/authelia-users-database.yaml
  - ./secrets/paperless-values.yaml
  - ../../../apps/base/authelia
  - ../../../apps/base/echo-server
  - ../../../apps/base/headlamp
  - ../../../apps/base/homepage
  - ../../../apps/base/paperless-ngx
  - ../../../apps/base/orion
  - ../../../apps/base/admin
  - ../../../apps/base/website
  - ../../../apps/base/openwebui
