---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-user-auth.sops.yaml
  - helmrelease.yaml
  - grafana-longhorn.pvc.yaml
  - grafana.ingresses.yaml
  - grafana.networkpolicy.yaml
