apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: monitoring
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:NTSOIeY=,iv:UKGnnFTueAQKSAxwnwyZhCAeO5OBFkTkZQW1IKSiNk0=,tag:muphA0VP6WmUl/xZ95eFoA==,type:str]
    password: ENC[AES256_GCM,data:UxnHUiXGg/x+mg5qwCBsw3qgatTl9EHXZbD0xrlr9K3C+dcHEfjYXI1/LIi6cJvK+2d7nbTd1U+yXnv3,iv:KiJr+lpglqGH8+vGrAoqz0hlzipKh5wSwzNfsKrcK0I=,tag:z+bHEbOQmgsmGA4bxVAdUQ==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNHZtQ2pjVmU1Qm9qUEky
            d3JBVzl5VTBZWnluamdqZUNqU2RxbnlKTVFrCklidTdhWTdsem53VElyZkQ2SytU
            MEpLcU5Vc2dtQnJCUnlJUXMwTVo3SDgKLS0tIDhVUlRwNzdiNldLSG1DeWJCS21Y
            RUlTN1pCaXd4bHBNYk4zVUdYSmk4cFUKYCk+htRvU7KrfihqrQ6FrIE7Zo/TUsPv
            9bfoQRBZhmdlR8csskxhEhgJmz9X46tPFaPKa+MoWfGaPnVnKBZnGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T03:57:45Z"
    mac: ENC[AES256_GCM,data:wtzcDORDNIWYmEfjPwbLWDZB6L1ARDa3w9QjfucZv6wToFE9JkjtCoyjf9l+/AM010/+mv0PSt4zKlgYIh2mTPg8MzgQP1QH+4Dxvxogq5YjaGK1jMigARFV3vT8zPNNnTizq3kM0TQAhwKWwp//n02Gie5L1oNloy26Z23axY4=,iv:4gpX7PcOXUnYovYD8WR68+pq8E9ZdPIx9/3iFNWlnao=,tag:tHGYg6fOpYKfmu/RXgCDQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
