apiVersion: v1
kind: Secret
metadata:
    name: openvitae-secrets
    namespace: openvitae
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ylT2sjfuJZkjqtHQL/Ht/OZBSrUbi6JsKbvi+Snjt56N/SwQ6KjvwMnS4/ln6spKeFZEYJ8WI8ipn45SryvpcXwOA2IyutQulKE=,iv:PR4fZKPBY/pogKwHFqyfn0FleVWIDBmMrD9yow6mUgQ=,tag:1eRmrVLLtjJf+9+0sqluTQ==,type:comment]
    jwtSecret: ENC[AES256_GCM,data:TPD2CjUiJael1DJYFghY+RBRWs31Awdz6ySI5US7uU6WMXBtLeUqP+71jH0Pm/0UAsnn70Apj6AwzT+1QuPvnA==,iv:tP58R1+l14gm/R+C1XGH/ISM9PdiWTgbrogMR7xUWoc=,tag:82bCTzjb08unR6zXfXXKoQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:XziJfLCDLm7LGg==,iv:XoBWfGeukbjtI5m/lxi9R8+zC39q90ZT4OBSjo8wTug=,tag:r6KWkYQYAGgBa0I400RG7A==,type:str]
    postgresPassword: ENC[AES256_GCM,data:VBKlDWw7PxBj7GhfanMhHeEhY3Po69m7a8F/Yo0xpm8=,iv:82SbLxG719BKXrbZbezly1nIrPm+7+Xt9CVOPvsf33o=,tag:+8pjg3DXbzC1ccrOUSxTSA==,type:str]
    s3AccessKey: ENC[AES256_GCM,data:IUQUSlr46nHA80mxdBhg69c7j35t,iv:6UfwFTpaHVvf86KTBTF8Vg/ACO+5gwmWhGYdHo2S92I=,tag:XWPHpFk8Qod+OXSKMl+UDg==,type:str]
    s3SecretKey: ENC[AES256_GCM,data:oJtC4yzkUIy0OO5bVtDFu3nhH9c8s5+Me3tx0T9hZ9/P/t/wKzGIcg==,iv:4YLs/jRQ3iqAqiD6FGENWnlXOVv/ivs7yhjDEeckiJQ=,tag:xvtz+9teRR2dpCQgD7vVlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBK2pkTW80dk9EdVRHM2xJ
            K0luRnBMYUZpSFN3OXZpZnNhVWFUbkN2eXpJCk5NSHFsalFkMGY4QlNrZDd5QlNJ
            bzZ6VjFKb05TVmxNWXQwRUI2YmFiQVUKLS0tIE90cHRJcEc2cnhweEwwWmtvOVFy
            bXRybGttcXM2RUF6THZ4TVd2SG1ZeXMKFXciapLSD+MR1/9WFGtV8y6LoiPmRVid
            mfL5GCMBVQ2dKqdcd4gJ/qLtdZTR+P+Nmejt9EkVwIBJ1zU9bZZpFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T13:56:39Z"
    mac: ENC[AES256_GCM,data:3Jo7c6f+Rg/GDuFgNzzoUb3AwakXFT3+BatxA7oB5Sd7q9OahHoCZLu4MSLOczRL38VOaQmmPhdVLvtgXkHgXBrYPVpdct4ZiKghGcfHnIySEQJn7dj6twMd//7RGD43OsDoFfXUOsMrr4cHlg3ftZsHFzHGwF7KmNNWeqRjCG0=,iv:0QqN+vJtMRKAL7SN2xCC9XAePsGynGQaXcXaXLv0OU0=,tag:f/onVVFV0hMi5wL4+FLXIw==,type:str]
    version: 3.13.1
