apiVersion: v1
kind: Secret
metadata:
    name: authentik-core
    namespace: apps
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:uWfTrkY5eruwQ6gZ7AxRoAXOjDBUYKAuiuaeRlWeIbsQh2bHk+U7zVn+UO64WDkf2GdDDE5HuXdNLjW28JdcXzRPG7xcquBoi8orGEbi828=,iv:DWsnWYw7tB57vlFUCqi1Uep6nkKaUftNyvYfTJ5caMY=,tag:Ofzk8RPSF46kWaRep6GqdA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD_HASH: ENC[AES256_GCM,data:pho87LYbFUCg/e3CZwqqFCWm11Lxv+z0liklIgx9wL5SNxtpCEY3KA0Ed82AKnxXsybwiUknlCVpBsdAJNjoIX6nik5Rt6IrZItu+vQSj4uaNlsKLBXNkAQ=,iv:QM0JrkBV074N6wZVd1wCmSJoY5yjL+K2TdaeP8jazG8=,tag:gFG5g9hz3mRlWbJz/xTPfQ==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:zrvZ79Xi7OHooy+69Z3bssDBV7GMwPcHpBzMsraEnudUcV/Vvwyx80F+epImk+CETXfY2sFNVRIRidWMvr0TPw==,iv:tIvfD82NeV3vQj6+bpN8i38UMrLnMDvxgy11B+Shxz0=,tag:UfSI45+FbIzFSuvRlhErAw==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:fz5VFj7xjXp6BY/jWV8BVjcSZ6/yQQ==,iv:lVjTJ8juGC5+UjCAwaiGs+YevPazyOhiOrjrq1UFTO0=,tag:17sT2b3H4CpVRIW2bMBL8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNnVicThzS01JdllUSWZ1
            dzZUdXNCendaMWhPV2ZkWXNqNlIrd1N1QmhJCjRqcVFGdkw4NE16QWJaM080TW4r
            Ym5qamlWaGR0Qm9jV1NwekR3ZUNaYXcKLS0tIEFDdVNJRjU2NjA3RGp3Z2Fub2x4
            WE1CM2FyekhycXBacytEYkNTM0d4WUkKLU7+xmeyE+ld88c15TxuLJZ7JYv+T7gQ
            dAskbX1++gDrp5fNX4qIOBTfLr7DNnnJmqG9IHikt2wuLhP/+rOUqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T22:02:00Z"
    mac: ENC[AES256_GCM,data:I/OtInZPHkaMk77A4HH/E5WWnoMmMqtS3CV4hP4fKZbuEcSSRDV7tJABhFtYiwQZYd1YgAITsC4gJlJRi3+6T4dXXZEtMWNWAeowR3RfCg+7RtxhxCvjwL2naM/rvsRNtNRq9RhjlOsETj7k9WzjD93IqA1yXtsyT5x3b0rbacA=,iv:oeybQANmElJxezVFzGdcdSQymC8KXhQ4Q0GJCShGUL0=,tag:KxVYrpOy58QNA5cG1HSQ6Q==,type:str]
    version: 3.13.3
