apiVersion: v1
kind: Secret
metadata:
    name: authelia-users-database
    namespace: apps
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:1iLhUtLvGCT+G9FZpuklXKCq8TsjPYSvICnS7e5fKIqWJ4atVCoBF1KQge7hL442vbFvx1TYSVD8P1xL4++bcadkfMwB/FIIm7MVsJx0324bQaJ4cuGWhypf/SmsBKovlNToDfKyJ1FKtaensq/zKK1Y4B+5bUTBxytz9fNUQvEKvK+R8ZaiSsq0DbSx4R3xc40UHVnbUANsg6JFRxDQTyMTej1ZKgowlZDkfCjX7bJegYbRSI9xhTYmoxMdvuAOiuEyrTosgRppkt1HyFQjhxKbnMzA96+d2b/ERUdxT19eyN98JOJt5dZox7U1erlqSis9fkg2ItGEbbE5PdNUQD6LpcqbZHJURtB2jPuksjhuP/8rb0BR8deDhkfiUSFNOKi9V52sb0ZEGA==,iv:fU/U/a+Rs90/zcSpUgUW6mJgLy7gzxsY2EKzk3oEhRg=,tag:hmdfTQDt3pkzRpYNjbKscQ==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNFNFSXljajJrMFczTjZU
            Qjh1cGJIeUx6RFoyVVUwOXNXUEViOTVBaEMwCno4bEJOc1pkYUdFK2Nxc2syaHVY
            R2kyMlI4dHFteTlzZmFHSkxWbWJsV00KLS0tIEZ1VTRFd1BIdEdyc2FQbjk0a213
            dXpzVTJhZmhMcDc1T1kwNEhIaE8yZW8KXS83hXrU+WQLhPssjzg10ntCTGLLDXg/
            yn4yp0U/dkQllOlK+EVTXg7kGYWAUJg1P+TkPbuP6S0Q2c8nt63ARg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T15:53:00Z"
    mac: ENC[AES256_GCM,data:qdzMR8FesHJCNtYZHfbiohWhTW56HQVwPLhoSSZy3IRshImFyTO1Rjs/fY+4roSkzPnofutrpKyVpGJUoOZA5RG6Ag7/IrkNU9oeiHqG6WCwb3aYD7yXlcMx0AayDK1AW+b2sFiVRIH8dyB+R5GUo3ILARiyEhR99kvRqTfVClg=,iv:9+IJXH/u1tJm+EihH/jjieYkhZ3CV2r8Xe8ZuzPj72Q=,tag:f1TbDxB3455kheu5yR48lA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
