apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgres
    namespace: apps
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:nFsS1RJ9+lqQ,iv:HdBpSch6T262QIosfg25bwVciytf/LoRrcEnTCinivo=,tag:ZPWWO/GAi48h+qNwQhE75Q==,type:str]
    password: ENC[AES256_GCM,data:vp3AuWqQdnQbJb2XwFKXnvDUX1t3qOtc4XNLY+oTRSqvOLSigczza8g77+l1bV9AlZdUrQEZhgXVSsSZzt2BHA==,iv:M/po4MegmEOwjRYEoiTPn+gFSmAUgkTQC0K6TKMcV2o=,tag:dYWcnK6dzgY0N1fFC7jzog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra0NIWWg3dEh0RTAwYUcr
            Z25UQUI1K21DRDJBd3U4dVdEVWJ3ei9Wam5jCk9QUUVEUWxVRXNTWSs5RFpkVkE0
            RmJqb2VmNUZqVDd4Z0thTkdUSXBmdE0KLS0tIDQzUm5GNVNiTUEzNUt4dFoycENZ
            c0Z3YmkxMGZRQk5TZHgvOEl5TUNLWjgKk1h6vxbxF+7MuKuI/y7Yx5l/8eMdC0P8
            N1lPitkPqObbjp0bm1DmZNdZSQgPUJ9jYc/js6Xnc8lFVp92Rb5vkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T22:02:00Z"
    mac: ENC[AES256_GCM,data:jxc6P20eY7RfIF4pWIDVeCkcxo0xKTxsKwo1u8/AYKlApM5GCVEC8NwYhf1d5z3qv0O3IejPRnpaT9sEcmzPUGWdikmUqfRdDUKCwwACh3WjfR25jcgVF3VmOe3Fbe3u+g9U5OFu9loRge49ReSy8JCf6m36iJi02goCnZ7tZu8=,iv:kIj7Pq2FAzWxvpv/Wp/LFPHU3Lg3Y4iFbTqW71u2cXw=,tag:4FBxTHHKep6PL8MKpQ1i8A==,type:str]
    version: 3.13.3
