apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: apps
type: Opaque
stringData:
    oidc_hmac_secret: ENC[AES256_GCM,data:o38hPLQhDKp7aMvRaiyc0TU1cH/fpE7gBRcVeMXIlWsknaCEVWQ4HbL37lyWJqrm2XusAh67+ZVYY86Xul3rGQ==,iv:zK8gIzKrmB37ICXzYX3SrKRSNQXhAqUQWdwIy07QIvg=,tag:vGBjS0f2s5WvvnkrxTAZtA==,type:str]
    paperless_client_secret: ENC[AES256_GCM,data:EUSq8DmoTeTtpPp5CacAXr8PWVkxQi/AjUa9cLhxpTgaUPxwKNd9T3WK0sDWHsJx,iv:B+AdQp7MKfqmkC7DuMNUZ5rR4MvuirLHRse7oIO/zbA=,tag:HoWJORYwgxzuk0bm5Ed9QA==,type:str]
    openwebui_client_secret: ENC[AES256_GCM,data:xXCHg81QHpnuFE0CjP07y3olm+6ANprMII6YCkuYSqs1/5WhfjlELE+IGLyWkTRg,iv:gAk1Fzg32+mOWw3x/z3ngj1oNxAqlhbu/T2kAO78Uyk=,tag:0uN9zwiy1iVmY2sfUwLtRA==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZGdvZ3hZdE1HdGs1QVhr
            NGE5SjlWMEk3NkJzTlBaeTJ5a0RCeDlIRHdNCjhCUG9PUUpaL3c4Sm1Od3ZqNml3
            VExQZzBSelVqR1l5bUxwb1A2eXluQkEKLS0tIEFvcXNDVjg2MzBuUkh4c0lRY2ZU
            dndrcWRJY0Z1SW1wNDQ0SzFHYVRURjQKXOjGUFnzzdwIyfZ4Am9oIZikC/3H2xco
            yi6XiCgZ5fD15nPlESB7tfnHplCu//2aQXvQ5rrL2YUQVC1CcKtd0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T15:02:53Z"
    mac: ENC[AES256_GCM,data:MvoJ9FX//cacGCsscwQU7xkjRYutLNB2S9NPPSB2SsuozaEefQCzcvulGhsaddGdE9JMCIIAnN9kqiuNABuclZD19QgGSLC4+EYz4IMH+lTZAYpYRzn1IW6NC3HUm01l6XtKttI2we96uKn7v1EUfScBarNgT2lCjlo+KMqQ/6s=,iv:Rm5BPxAjYgMZiEhz1WCfR55kqDHx3wBSrk4erHgoaOw=,tag:MCG0Ma7RD/GxBS3P+E+rdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
