apiVersion: v1
kind: Secret
metadata:
    name: authelia-core
    namespace: apps
type: Opaque
stringData:
    identity-validation.reset-password.secret: ENC[AES256_GCM,data:ycSJmb/L+vxr9posGHJPLsjzlJf7kR6SSyLPbuAm27o/pKR6jUchcQgi42Og9xaZTKRd7mcXIMH4W37KlOq2OQ==,iv:K7Ena2TBzXZv+Dbr6xgB44ZdLpXHZMuLuFmo0N9aF1Y=,tag:X0+jzmPDbTto/L+vV6TUbg==,type:str]
    session.encryption.key: ENC[AES256_GCM,data:ltb+2BD1CgmtFglP/+EDQ4f7KUPBaz0f3jMA42ncoP/b0lsrscewQP0HQIpDo8tVV9n27C9H97YaWRauzIQK1g==,iv:sXI6moBl+zA56cPGo4a0s5h9h0y7hnKqr2fqMqwnyVQ=,tag:5K613UNTGbQGS32VKKUwTg==,type:str]
    storage.encryption.key: ENC[AES256_GCM,data:MzXg72OmuaDvN1Zost7fq/ckr6cB9OSNQVKaufMyERTmGYzrJFuxqTl7U7VNshx4HyTOcPakzJgDfbV4wj9NBQ==,iv:g9sZbihYFvafzgqVWdjZyl7XLdHrMqsXxj+23m9SkFs=,tag:0inFRWKSw0QBsslxBldOLg==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K001UWtrQW9IMVI0Z0hX
            Umd1c1JRZ1pYQVhjUktPY014SUJqMDNXSG5vCjdEZk9wdm5DalRRdFpmNy9oNzZr
            eS9XV3czUFBMZkVlTFVYU0hCS0QzMkUKLS0tIFJCeXpISjlFcGdmblhrUnliNHdZ
            T1ZMK0xFL3dRd1lOWC9RWmd2N1llbm8KN1J0B4TYbUR1ekn02G4APAbX2c66LuFo
            Br/PWL6twD7lwJ2eMeZNzjnqBwWVvzo9+ysqvgAD51OdkoFKXN5KyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T02:54:00Z"
    mac: ENC[AES256_GCM,data:BPYkr5nm2tf9ZFwHYysm74qobc8Hj0hi/w0a2yGe3cdrB1+aO7QIHZi1UI9/p3LHext1nPGma6g0fKS9GIyvqogO1N6GYwLD6wrWcRLSqNtekinBc52jHTY+1A2EREGB6ziFLcSaQ/LEylmzCxWilyeQzdISZY2byTcGIzRv0PE=,iv:gzpRduq27d8BY2QiavS1Q+cKlEWChOIFpm8OcdoNYtU=,tag:t/UCSAVSSb2wLbJNPcoAAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
