apiVersion: v1
kind: Secret
metadata:
    name: authelia-users-database
    namespace: apps
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:N8n0GjbiM6V1R3spQm6J90ROeWWWF8qNnBuKghMvvHHpkhvOvj56xg6oA89ELx6DJf2E3Lh12iWqTXm96kC0t6Kn35Iynm/Gb81yZiyiuClc8AMcMd4LgywcqC15n3XjzkxUDmTHym1m2sgB+vheD0YrJJlNO7ea9uQe2Tv4XvSU2Szj9Pplmx2klELwL3BncMAWDX7G3Eqjg9VpU54+ecQvS4UcR4Nckgpr4VdjQVUlYl8Q14A+rttrdbu36nw0xpvOc9B6IRVh3M3R4gd2yywmQ1vfjhzP5YnpgXd2U8Q4rTlYrhB/BNG3+32LSjlwm55gh5tbGGz1m8zcKPLqN+5KZjoiydJ/nQ4Zc+/CH5f7lccC7B0M0VzAG0If8IBLrRItwvw8EAU+0p4LxGoaw3leXnEfj4VEE6FPGH3oLFiJofUjHAWQjjlXWiYcN3eLx0kA7WU+G+zWF7qCdHFvIDZ2RHp8rPR1vMDyo/FI1+1jotpf5by0vYnQEFxeyLx4W2U4wgj8GmPs8iM32vb2eCzkP3M1kMAEsuW7oAExjDSNnWcqPne5tTGgI5e3YQ0/jeBe3+wN4V4Gcw15kKIBmm1fONicIwewDksgxg37Tq1b2wjX+qYN7u0to8SWnxWjPRzSLYc4JFzFRjMZ5Trk2cx2GoFVZW4l5TFJcBkYbb3dhyT1oZ8rqWu/ux1XxvxotNTaQsLfkVRlL7IKwhS1WuwWa5IlPd6T5iAbQQHy0sBQNh4lnZWfO7n6RkJdL5X2f+nCw0I+0LE+KneChNKDzZ7xQ0RLTVn4yYnM4GH3ioEejGx7Y66ZjjfWyJdqJb1LrOVP4UA4mP3ZcoEvFIpYj64tRqJwOrWQA1jjPteYbWz1r0r3JkMOfSC1lYHs0mG3d/hFg6aLzxCBmK5WBy4/q+/ezUWAoSyV5GZRgXkS0MNsTmHw1jlrA6mK98muK1WyCfE/kPHW4rnXx4sTB0QnO02lW3ZT+L8UMG6ztajVDv2pArv2EW6z96v,iv:xIik6jkg7JK2Zg6dd4EUnJ0la+ExTI/6x09+5yrmUf0=,tag:rhf1SAXVHy+FtNnGSndqLw==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSCtta09WaUdDSGtRSHA3
            VVJVSmQ4cHhWc2RNc3VwbUNEWmJ0cll2UzBvCnZNTXRhRlloV3VyNmJ2eWNvM2c4
            OXo5amIxYzVkWHhKRlFVaUJNS0xIWkkKLS0tIG9DdE8xR3hkVHlyM3RVdVY5K25w
            Vlp6QkszRSt6bFlMYk43KzRuSythNTgKQxWcvzhSvTPM/H3Oz8M+7+S+bI2sf5z+
            mjwVMWwbJM/6eREn+6xtg8dmGZCFg0G06u8rNiOefEJwvzrzT2Jt3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T16:08:43Z"
    mac: ENC[AES256_GCM,data:HZn3+XAsT5kBrRBEp5+4N0/pgfIowAr4zrB+06jbT96iWWTc/MtJXFVPVzOxsc+VgLEMaeWcZDAhO9t3bu+hRbJgF6CszQgq6GnKJfXe9zOnExHCUNFkB38Fj0xcP88QebnX3jmPs7Mp07oTsPTAUZ5XtDJ8DUaGH57l/O4NNdk=,iv:lm+TUbRLvdRXw0GfV6N6wrqYqpIIQkGfybrM85Y1ZKQ=,tag:ZLzWkOg4WeAwCTYwOHuLmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
