apiVersion: v1
kind: Secret
metadata:
    name: authelia-users-database
    namespace: apps
type: Opaque
stringData:
    users_database.yml: ENC[AES256_GCM,data:aUT29bA1UlE27R1I9kk7ffQkwNwcVM2nCzcvi6mMKNHDW2B3Ld8OgScsA65QgzULWNy/LhD6UHDLgjH/+WhN8fHw7TUcXchwZ37vnuWIjOzqcrts2gUzPowe09ETT3M+93XBEkzQAkpguliic24A5UTFZAnr9HkMsH6dQr7VTCrzwdfcALZGGyQCT6MUOLm8LGf9lNnJFhl+peIL5wYUdOwYeQMxZqiiaRxYYCfnNjn4JcWjuFh4rhiYOnKm6U2FYyCK2AfrmJwmgBpAwaafAmiEbGz5H1+SYIu0tK0NYS/Wtk0L+ccBhw0Qxc4slW1SWHoGcFseqA7S8CXlKhDTh4IvW4ww0osrjTfq5lPo8XsIXo7bWdmDVMdauEYXD2H153c5R7hd7tnN,iv:ACrqmYbTlpRYQ+KtPUBv33XTou27JMt/3rfyhkdDYW0=,tag:L3SU3h6y9GudH6a0RMmgKw==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtekFlT0x0SmhieksycFA1
            dmdJQkcwRGR6ZjBwTUc0SDRRUWxFV3VzWUhZCnBpdjlmOUdkbU1CTXNNZlZOOXl3
            eFh1dVVYWUwxWkkrZ0RZNDd6RW1IYUUKLS0tIHlzbWtNdU9jNVZLUE5idTRPN0xs
            aTc3L1duYmVURFNuSENXSGFMVlZaS3cK5CqqOgXOom0njMUOMH3UOOpyesg0+4GB
            42D0aVR4o4gCPC1VP1NUDwX/TvtWvLqxGh1dqcbi6Qo0NBxfH55uCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:37:32Z"
    mac: ENC[AES256_GCM,data:IeCK6mz2uTM3DfxYXGV/dEA9XZXP+0rjGaEW5DowZKcA+bZBuKmbEiPYfUk9gZ5An46ciRkiycLxCOTpRnjH1imnCIuCDCgCcm9zAJK3vCHAobSaC+phC4p175k4wuWfRS7uoImBmL5kTtAIPeCY/s0L+zEQ2Qk47UgomgVdZVg=,iv:UMoqsJpDsSyZcttZ7J9nTpneuOmhOT4FOlThZ13/QrA=,tag:n0gyLzVI5RbtdyB/Xnit+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
