apiVersion: v1
kind: Secret
metadata:
    name: authelia-secrets
    namespace: apps
type: Opaque
stringData:
    reset_password_jwt_secret: ENC[AES256_GCM,data:YTQIEtV0+s9ZXuH/U+XYtSuUnU23q7ACDh8Yx1IzW3GIQWZXnJOqt4EkqOazc0q4FnqeDmHp/cb0ALjPoXFQAw==,iv:8iEmV6ddINr0T8AFKrF2W57dj1IUm5+pVn7cM+Jt2gI=,tag:0MQEYJYnXFZPWB1WnhboZw==,type:str]
    session_secret: ENC[AES256_GCM,data:XgFYQPmkNHWhrv5YKHPeG3Y/QsrCxnIJQg0CLO1cZXDs7FZltt5zc7GK9qhol0n8eVie3mbUG35GGYha6GHroQ==,iv:lf8JUaqaVQaK6ErqktRtNmOQ4eREJCdnKKg06kG4LUY=,tag:g9QFM60HNCzfbGWjqhLw5A==,type:str]
    storage_encryption_key: ENC[AES256_GCM,data:N+xZ1ny5B5Dnlm2d9zWIKKfi6vyM1JUykVqZ/ybjQ61GQJG1Qq5hVMUtCq4TSLWX4sqwn9qDFsGbSXEgZwncsw==,iv:K7FQ2+1PATx8WSsx/M1xjSjKK96GalSyKydhWjY+pHI=,tag:LP15ELt/ucSxtnlz8wjTbg==,type:str]
    oidc_hmac_secret: ENC[AES256_GCM,data:VoRsW5V2PXJPHzO3lY2OpvWBt4Ac+geCz7yRl0YCs84WE9lPZBUO/603SYyMg/hs2SIyfrSOb2MFmoqDlIyjlQ==,iv:sVglOUdZb18EKZO172z/8cJd6e47BkaV1Uznrmiq8I0=,tag:DmhNF5/7j4Wwh15fOQ59AA==,type:str]
    paperless_client_secret: ENC[AES256_GCM,data:evS0YR2B1Y/3b78xUUDhXnLwXinV1hMc5nfaWevLktmsPWIjQPIKJsB6McP71BUd,iv:D2DC+j6jnG97Tgf0GSYorAleGIePAdEattqPf5sRlo8=,tag:VDvrBHpiNxVkMSWEoseRPg==,type:str]
    openwebui_client_secret: ENC[AES256_GCM,data:4C18NTUBugv9Yu61BM7sAHibl4oCi44r/aVmIRpUHarHDpff8yFt2Q+bXNLzJosP,iv:6kGjWr71jMROhLudU7DY6CNsNhKfi2ls0XmiqHDZUOs=,tag:nUPizqsr1TgEO59rSWmJ6Q==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNTVMdVFjRFRtcHJLM2xM
            YmM4ZzVaVnUvWnJMTEcxbU9oRFBETFYyL0M0CkUvOWNXSHU2blY2Mnc5VytraTho
            cGxOUnJuUlhYVXJJb3l0aGFNTFhxTkEKLS0tIDg4a29DSXNIZk9iZzJBVHBOZFRM
            S1dDRnZtUDl1Nm1uN3Z4Vm9HU2JBcDAKE9Azb4Oslp+WYb+d+daOx+15Gr/YAq/L
            TIQn7BqRDmyzVgH9PFEreMPB3oETDtsFMMTkd2EqihDiXIMSHh4heg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:37:32Z"
    mac: ENC[AES256_GCM,data:/b22bRaCC7/B7PCum+DUz3NcsRZ4CAKVBeCh/hcdvd1wipYMTqrTlIfGhjH3zoSYA10o3WQHftE7EpfAVXQE/okwWZBVQ8p07LsH6FkCmgKYZ7fjptpESiBM1cQ4jOubLoYiOqg/Uc7kH0cUhUZZ3xOicMYfAePr8kwmc7TiCqo=,iv:uX+h3tS+q1UjsMYAMupqCIqn7GcniJ3DG6OJ4rRqtHY=,tag:SdFKcFjwZj1oXxVxqMcjgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
