apiVersion: v1
kind: Secret
metadata:
    name: authelia-postgres
    namespace: apps
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Q8HhTQU+4+Y=,iv:p9LhJGDR2kWij/DIU/gqgAKRh2J2GLfPfkO3OJ/KlzI=,tag:jzwn3dV6t63SyZKqAAYUjQ==,type:str]
    password: ENC[AES256_GCM,data:1SM5AgjV80N4hF95XbKgojgI+Zj3ff6WsBwBaxWQ6tELnT32erOn17xhY9PEiiFfYIdZZ4vA8SJv0Nt5qlkpuA==,iv:PEkTg3QcseflfgVOhZvg6lQ0N3Y7ygCqwE1VvDK4Y3g=,tag:KO64KSBSuGn9OXz0lAkFIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WnBwQ1UxVUx4RGxyYlJx
            S3ZQTExOWmhwZjQveVNVZURtSnJ5V05jQW00CmR4VmJnM01KRkJ4bDBSVWZNQWpC
            RlZMNk5ZR0hldW80anBHQmt6N0VzSW8KLS0tIHFsNDYyVjlXdWdxRkJNZkMzSWtp
            ZzN3bGVMUW9kYXdPU2hXSE96MUI4M1UKpueoiJFsYwrSzrio1o7InsA2QzVCK3qN
            If3iDOEDhIIxUM4Ej7xczgT6zYCsUGyLL2L4gQxDYuVb6doo9GM/Ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T19:25:16Z"
    mac: ENC[AES256_GCM,data:ip6UjjJCM4wvrEA8GNMINj3eEcEYDs5LhUF4JtLZKunTA0BRiu6OP8VDfCK8JEyf8pWRwJKruLyJSjhLdOJgNUG48FCwM0Tnb9a9cyQkPqlvaBGHBp2DZa6K8ZIIrsCH6kM0Z7bA0IiRVrTgvTt9sJ2XDY5S64h8KY7S+tuY3/A=,iv:G1cZrWrTsll2+e3Xei8qEc3erPVUxn1n0teUdxW687Q=,tag:uKs+aR8xJlfZOAdZPBk7vA==,type:str]
    version: 3.13.3
