apiVersion: v1
kind: Secret
metadata:
    name: books-smtp
    namespace: apps
type: Opaque
stringData:
    CLOUDFLARE_SMTP_TOKEN: ENC[AES256_GCM,data:MQjE0NgqrJQ1o1VacZFneeNaC62pHYq/vc827SimMG6FbbjsATBHDsEDHIVxJRiuXFnL53c=,iv:XOhdsjautPA1aSZSMLKe1/w97cFK0QqGEW2zcpfX8vY=,tag:1G4wyi+sVnddPptGXk+Fxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cVZpOXRCUVFLbGlnSzNZ
            TDRFS05ZZ0U1NitjSURVZFV3TG9RRjU5TWxBCmpDM1NwbnkwTm16UGhucXhURnd5
            Ym5Sa0l3MUxCdjdXazFuNlZ0S1lJa00KLS0tIERZc044ZTlQckRtZU9udm9hdlBG
            dWtLb2F6U3d3bFRkWDBsczlXd2hxUncKM6vbBDI7r0vqquSGrcQpgq+b0DO5QFbi
            e6YZcaSuktL1El0WuvPx8b3LZiJ6jiGQRKJp1N6GZb+8Iv95itiItA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T16:12:19Z"
    mac: ENC[AES256_GCM,data:YUoUa3cJe9083OO6ZJBMWcf7SoVo2t8ExAXYfaSMc7i0C+JROl9z/OoHuxGTnzrqC/Qefr1dRnLBkm/swRyr7vjjoIUiVtscf1cHjnadSHhHPmR7Rmo4mjnceRyCq7WEAX3gRd8XHFNHR2hR2e5zoIF35j5mdeeKG5H8hJzjZD8=,iv:ulSoW6tEsOS2bE/2dxjiXEb0Nv8Wq5RjJfKVPDSpbjU=,tag:QZ4WkOCpmG41najg3t027g==,type:str]
    version: 3.13.3
