apiVersion: v1
kind: Secret
metadata:
    name: books-oidc
    namespace: apps
type: Opaque
stringData:
    BOOKS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:8JjYBPlvipZCkc/0sNTepP8aeoHEPb40WmF4aM2TFLc=,iv:rzqXbrnHJXaGP4Wbiu78Uvr0YwiCKxrj117ryKcKhb0=,tag:9bQEX0AJvF0Yik8g1WVWTQ==,type:str]
    BOOKS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:h5V81UNbBpJPiiXyxZAeGyyPe3CzuaMoaNP+CjYqkeVndD11zeJkRmTbTf2eG+u6Gy40ukPS8mWYN7Q4nMi+8A==,iv:X1yvfQl2OIJa1hbaTrxc6TyGs9WgPOPxxS4JV0JwABE=,tag:ccMzqbHFJVJLoJ1pLZdZOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUzdwU2V0OUhyWTNkK0JJ
            YXI2WkNtZlpvR0o4OWd6RmtmTk14M2RMUFJNClgyemsvQnRFY21GRTdIelo3bklT
            VFI4RXB1cUlkMWQ3bmgwZFNFNjZldHMKLS0tIDZzYnFaZkg1bC9HbTZSdDNScmNG
            bnFiaUVwRFExb1c1TWJUM1pEOG1mSnMK/NDU5vpg0S3wV8CHVY6LJt3Joj49IpSs
            GGGrWjA7jXDz7IOBPwg27DI025NcnI8Avl+bBTOIJL8jyVVKa3k3gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T16:12:19Z"
    mac: ENC[AES256_GCM,data:GpvfV4YGuKskJlULOuc4oEmKDzPzzJN2ifJOuaGPGEOGGLXZje0DVenUsxUaGYW121KqVtYahJ2Xr3T8LcetyFPHCjYVCFg5pwK26v3zs+7tHf890Kxjn669hu2Eore82qdfCA8tl8qJO4xToP+Nq78bKIuBun3enno001UNQGY=,iv:EDfwyECvGobvQGhhny+UVoKSj4cgliVvVy/4IZlnvn0=,tag:99OyoRhS8XYYkY0gjRxwFQ==,type:str]
    version: 3.13.3
