apiVersion: v1
kind: Secret
metadata:
    name: books-oidc
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: apps,authentik,books
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: apps,authentik,books
type: Opaque
stringData:
    BOOKS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:gMtD9SOsB3D218WIO3L1ZaAhWOkxbKP4SO+RsITw/P4=,iv:OGpvf+E8940lPCBWL0T2kvpE5Goof1jMoWPjOP1wc3M=,tag:9ASKDAz94e2KHrNOP8tAgg==,type:str]
    BOOKS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:25BtXyxG91ZduxbY7CFMVCc702i3wdY37lYHP/OsZEKbFjGd0rsQ9ozqrxPXNiDON+S98E5TS6SjJs7c1Tcb9Q==,iv:LY6txbNt0g8sT6SsQLKAOuMt3g6UFut0RRe2dzzGgjY=,tag:cnM9MNOimPHVH+p2QRqHjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TnRXanhvRW85bkZuanp1
            UUp4MnFtMXgyQktxUVpmb2cya1hYOHJUTGlVCkIySDl6eGFEb1hKSDlkZUtrcHBp
            L0llVEtTdnZYTzZBRDYxSU5sd0Uxb1EKLS0tICt5VG9qT3Vab2JXZnFPSzNxNGoy
            UjRTM3BsMlQyUk9tWjV3SFZMUWdVcGsKjMb6MvZl4u6ZKl0KH1GTc7mxJwtGMKMW
            5B8cNfYhX8HyjRyOO0KetLJo5bA1BKe6BKsXDDuOVnKqNNSvB4a//w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T23:23:10Z"
    mac: ENC[AES256_GCM,data:4u2C+DDoaghgSvUQlNoGw2v5gRsax8mtu2j3qzQeBg8GVx+i7BLAOR0v7lArdBfffRPYIFaZlkkVb7p+5jY95ils7hBi7rm7/5kdINHPtCM+XV+BR0jtjbBlD1VMZBrUJgVGIwphnIPI+vu/4embwx3da6h+XlyMOvN/uc67q78=,iv:ongvPsqus2Y1v2FrOYtALn3tW08qxXtjgkueOXZQHB8=,tag:29NhJWOx14cfZxbsjxXtrQ==,type:str]
    version: 3.13.3
