apiVersion: v1
kind: Secret
metadata:
    name: books-oidc
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik,media
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik,media
type: Opaque
stringData:
    BOOKS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:24laY+KfqrA70dV+Yhf0FwUeqXYKZo6wOPTD3CyDeEQ=,iv:7gGJ/ocvpTUD5e1RE5HDL1yft4WrQDGPBAW+eQ3yDHI=,tag:TK6TdHdn7rFceuMl2z5tUg==,type:str]
    BOOKS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:oFIKw8ajb7ufJ7NTnl5zHlR/Bw87Xy02qo6dS5BJbEz/I2WV6nt4Pzk42D2KBNUHZHRG+SITAoVaxaCtI8G4gA==,iv:eYpGKZWzs+PmXaQX4ri+0hdsYEmZfmZ/lzMVxqqsjjI=,tag:NOqiED2eInZWmhckNVNTSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacHI4Y3FJVmhRU05lR21O
            Z1RIMjhXUU5iMUdBMDVLb3VGdkNnanlBdzJBCmRKSmdLNTZTYWFROUZDY2lvZE9P
            ckJrOHVKOHRjZGdyaUNXbElSTzJWSkkKLS0tIHZGaFJ4SVdGV2hydHE5TFg3ZzZJ
            clAxVjVlZ01yL29JQ0J6bDdyTkRydkkKLsJhzSr+Mm5j4JQhqFpCkvu8Vty4vOx2
            jBTCePEzQl/MBUAwtgSgXsdQTC9s4g4nAMnl0IFlyozSbBPdbnEzRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T14:10:04Z"
    mac: ENC[AES256_GCM,data:3FIZAAU1Ya6lfwZW2IvpzKPf7kaYhqP9XQgurlN2gmUMUUu+YiK65WAjbRQowD03b5c28NNHaAvSQ040p8gZtAyXAWiQpye1MrN0BjiiUWGM69cyEXomX4YL4tzDBGDdTpCKxkZQZw1zJkfc1xoRQmeGy3iSIskW05xYaHDVf4Q=,iv:f4+awGvvwfoT6x7sTXvbp49tS9QG7TMF89VbLULRdEc=,tag:xCN6I96gm2d2xmRsc6ekrw==,type:str]
    version: 3.13.3
