apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-smtp
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: media,monitoring
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: media,monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:CNdysPmZX1r3xOVin7y0X8F3VoXAoz9WkRhQQjfPBJIPtPwnocn/pibiPsanStc1PTU+9YuAg1R48wgf0XdDkyUY6arx+I8RGc46ND61G6YzJfw=,iv:db7uMt6+M5/p88az/cl473zOtP51/s1tUcX6CC1nBBc=,tag:68A/At47Z4O+xtlGU8NtOw==,type:comment]
    CLOUDFLARE_SMTP_TOKEN: ENC[AES256_GCM,data:izpEguezYNtoyi0pEVCXO/0ZXAduu59nD8zH8rSWScSolPzoCIBpxrQ4ygnWWZ0tTrihCj4=,iv:enChwFdjhPFwxZBot9Wp807aJIcc+wQnkOGl22CgVoY=,tag:iFI7xEtVugm4emTedmiKQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTGpla1pWYS9yNWJEUzJH
            K2FkQjlMOG51cnZTSHhBQm8rWnlxbGFaTGlJCnNoWG16azUzdW9tYThNQVFkZWpI
            QTIyVUkvQm9sbm41TGM2dk9WNXBRRDgKLS0tIEhndG9LUkt5NVowM0RLbXhESmMr
            KzBWS2FyOHlFSXhjM0E4UU14U3A5NVkKC9C7qcjXEmvc4eQBQGHSmBcVPUqiROJ4
            VqX+IMHRmXBiBp0vGB4kWs9Nf0Svdu5fmsyJlJxWk9UUaR+O77HD8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T18:28:44Z"
    mac: ENC[AES256_GCM,data:WQURzNDb8FsS/gHxkwg6qdrBd1Xj+DXEsRw1fFFYPOdYjXGluxvaXxkGfpvRjXNfC9E3wGKzUE+cv2ORfkvmcVDtOJ5CmGLYNrdH7A2ilkn/WwgcFg/QnI+WGoiCgCzQOQjnRXWtfis4ggTMoMnLVdNLiS/Mp0PvDv1ldSeCuQo=,iv:C8/Pskwm+qvKaz9sKLqD/wwqejRqxL5zNHcPwsD7ce0=,tag:Dns1vcrkjciRtLtzln6+Rg==,type:str]
    version: 3.13.3
