apiVersion: v1
kind: Secret
metadata:
    name: frp-token
    namespace: apps
type: Opaque
stringData:
    FRP_TOKEN: ENC[AES256_GCM,data:mmrJg9SjxdfNlKW4r2VFqmlkGWhq7FG5f4yladtPgkesFU/M+qn95nEHVvguLm6g,iv:NNl5c4MIMwKD7siaMMgZxqCU8iPETcMTfIas5RDNVcQ=,tag:uu/Y9hfcSNMDCs3Il0gxGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtR2pWaTFLTGtnQ0x4cHZL
            VEtzaXF2RUxvMkxKYU51bzZCYUdldmxhbmdFCk5ScGsxVVp4Q1Jpdjl6TDIxSlZ1
            dDdKNWlXRDRSei9oU2RRUTdWN0Fwb28KLS0tIFpRRG81M3pwK0lHMlNxRG9PUU1R
            S002VG9nMWwvSlJXOE1JLzkydnJWNmMKMqie7ob0Cj0nhcaaywbMVQDEU86gsKPF
            aOAK35DdM/Iw0NQYIBCrjS3u3TG8XkuW5MddKPgvDSLTqioKhuN6JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T02:25:49Z"
    mac: ENC[AES256_GCM,data:KnV8SnE5LqbbGOTLoJ71tUnQ85nrucGL2KpMyLcC/U9TPa3oI1D8PzpuHE/NB8fKL6uK/6ijP1ouFobgNI3hXwSbkvTUX6jAqrjEjz0PlGGl4A7vuYRbX4jFDKVC/Rk2mtomaAQCehHFlZveoDjHAWnr2oE9+s6nxR1368rLCMA=,iv:8iN1XlZfAT9sE6hNotXmMXSWn4Srkv5lsONAUCMMG5k=,tag:Ywsl1QVdDlUe+PDPps9S8A==,type:str]
    version: 3.13.1
