apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:N4XTq5/K6Dc2RS5IhvUovrIcST9TYxToXWgqzX/nS4caoTtyn0NkQih65Xkz5vh4sy9diOJArjikfCelfmO4Le6NPXpvgmxoPXKlIPV/CUbaAfPfVQHCbGmJ7u3zcj4S9zlf7rE3OcQKUnDq8i0+bqxlU4UQuY9LZEP4ztc85TVkxGlLOXi9zCfIKRIR3jepsQWMhUvWqRDtiA4muuMXev49EQ89AL1moAWIm7eKxtteYHA/u8s6tYO4VHAy4AEeNet4rQq3h+E4UTO6Re3YJrBwBTxSfEy5iq083KZuFpqt5XwCEybS/gS13DWJD9eQmRBeLbUhXdRtLswTN1EIkGCU4djEp6Zbe+QQ1Eitql/req4KIyvDT1oKxChId2ejXPGqO2WlbJqdBw7XfeZ61A==,iv:tWeJ8oEWrnII93c94ckUO66poSaOtw3+Ah7Fo2hU2XQ=,tag:KgvAuo+tCqI/ABgVT/Eyjw==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: pigeon,swing-thoughts
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: pigeon,swing-thoughts
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYzhub3hIRVNUZWp1ZjZK
            N0owNXhQdC9pMWVvdDZ3cW4wcWxnd0c4M2xjCmEzdHlrdnY2VGdsREkrZ3V2dkYz
            Q1NFVzVkN0w1L2ZCVWJDSlhoSGl1Q2MKLS0tIEdzclB2V3hvM2JFVk5Ha2VONXll
            OFdrL1hWU1lQNkt1VElIb0o2d0JxZ1UKXxX0AS4ci2eklAekT9NCV6Q8NNypCwyr
            BrtHlEqoT9tU38SJhqzJf3DJ9Hnv/E/mF/WOs/04bMiczIPCU15kow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T23:23:10Z"
    mac: ENC[AES256_GCM,data:CkPUwPlbndgZZ1vgKuY8lRwmPHFzmlbvJM6WcwDocqbmhKY0NLLWMkG8A6ZLV30GmCHPSSfYyNxU1wQo5x5kI5HD7AKn7UYFzAykm+xQVRzNRMs5NyitNVOq1UScgKZeVlkt/jWZ43q2naHHVCQZmXpNYCSGWLs4a5iICpTQ0E0=,iv:KF3mjCYV/Qs+q4JgElSD66Ub2KCtOUJcKL3oE8gvfto=,tag:L32LbIf9L4XsYq4N+OZCug==,type:str]
    version: 3.13.3
