apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Rs+mG93ItJD5wzlUYjMy9fsdD7DTkAUa86mme4B+hv60PoRIXTHC+ggC4Jv72RQqBnU+hAxGSjpfRqXfdhqwI1B0RzqmTOFjpkO/JCQT6siW/PmBbNko1UbveiHQ1t02Ur7r0C8T/2+AA3wPJrNmCShdVPgmqvacSp+dTcFFM2LV+lL6RTPwMIdsttIyDkzxYTpQSpBI5Qyjst1+v3/XTlfryuKLxzYXe4hzew0z8Lj3Oh8TTXvdFyr6DwiOECsXUSVw9uKCgZuEkoRnp8/kWcx08DfuP4CliZDAs7o87E6DN6Hv3qq9wQ3RokroiqTOAuNaSWPm/pbJeIJmFMKpYH/JgkusM2UttsgCe3fEj88cZBkjWWSxROwE/Gv1r3NOlJn5cuwJ4QL2pBigRLW1hg==,iv:73PqXlo62ibAmghdZ8BBbvUUAlsE748Ri/fWXrL2ly4=,tag:Wc1xD9go6ooxHeCp1Zl2ig==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-pull-secret
    namespace: apps
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UThST3hlc0hZYXB2U3BH
            aEhLODFJcTZWQitySWNQR1JDaEg3SkREa0dRCisybTZXMU1OOFFuTmdOb3lWQUdK
            cWNaYUF5RVRaK2VQait5cUhFRERXZWsKLS0tIG1QaW5KNlkyeTIxU2JudWtUZGVu
            a21ubEpRQzhIUFl3WnNZWlJ1NlFEU2sKvrUFZVkG/aMAIMI8XvtxiclXprLCqUib
            8hN8CVPwCVJ15/OOc7tBAa/pfIzS0+0WJpng1ZNAO23nQ3vJ42pHlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T04:37:43Z"
    mac: ENC[AES256_GCM,data:jDH2c4QGe/qOZ199OGmQmH/rYtITuaYvxnJpnB5SbbPK+1jccgcadZJWo0al186ZrmO38krL89rjFY9h/KXKwNSRG1eK2zM838sydnhX5+tCkySKYEXNXmQqJeS2O+ybF7z9l0F/kujZAOnRNwvdalODh2a5s/3O47+EWDE4hUw=,iv:UNiikNEFxHtpd/xw/b5nR77C3Jd3cjEIHy8l7bhxCdU=,tag:RGScqQ90bhrRk0XcF6r9sw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
