apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: apps
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:e9y76j09UB2MP16HP8R+0b65/uyXHv/FyP8mQ6rfpnSiUGBh58rlE6eDOtiJVUHQYQTd+X2SqwbBI27Eql5k2T6IJS98r/ogQ3rWqU7QQKBsVG2ZqrMcPDCRmWHD6o3aljxKl1WkaIvvSyixVVBA26p+hCHiXMEHBTaCux63pf/C/zVHGviQQkEED7Gt/veQtzd7VwnONgYM1ZsdAhvek09KdZipPlDIzzfy8WXfnKblosB5F/18Jgj0gij5HfgdZQ4FY3sHb34QHVf0yGYLw40gL68bw8gn8Xd0uaAZWD3VmTfCeUn5w65A+3p0B/RJ0JiUwx8gXQnnKQaUfIEZp+qDeSYpPYG6HPmDMPOWhExCyQezMkdBKO1XlNbci0N26E59eZx/O+RNXtTIeOyckysmPsvwhYVp79prtfEu,iv:1/A7+5HXRwwGyl0JwvFdJUq5ZOUDay7LCxeM9me36IE=,tag:NvBW3onoYavbW/jmDvXb2Q==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaE9YZkR6Z3EzNHNUb1dH
            bCtCdWZhUzlhb0pMdjJ0eXpwSGUxSE9YOFNrCkFGdjhKYUdmc2JpQWkrVDltbjJy
            d0NoSDhoaUF5VDNCQ2xuTWZScGZYM28KLS0tIGdIZnI3OVNQSTBPY3hlTzBpR2Zk
            VGF2NmxLNGlSV1o2allZUkd5L2FsUFEKl4HC2yDMDlSV18fadhqhmB4vtQ30BsTO
            ZMfqpY1X9IIh0IjYFgCaGNdfZspLZZ1hqGEVopYXdAzq2kSy10AcOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T03:48:57Z"
    mac: ENC[AES256_GCM,data:Maa7x6npZodGE3UbSq5xEVMdaByv9xjbp8PL9rmNigiC9zVdJO/L+F6KR5kPZJR4tMRg9zwz38F1B3VEHo5vF8/lMEKXmSHayJMoMH81yVYZUnUG4pd+3LAQeN1iLlsu2DNoVe0AfVbWSOAZ0Y+XdOfiM1iUNGdyJ1aMd16TNf0=,iv:JQsGTFKFIedPsx0UbyOUXbzsuuqYXdUajWRhBmRtHqE=,tag:jeYP4mtD0eFs1UlVJenOQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
