apiVersion: v1
kind: Secret
metadata:
    name: harbor-oidc
    namespace: apps
type: Opaque
stringData:
    HARBOR_OIDC_CLIENT_ID: ENC[AES256_GCM,data:Ao6EbIXX2NJqO9jEfNmotyBuiWfLnmsMs9zuSjBi43MWeI58aKG5hQ==,iv:OfmRxWPjulB217UwMjo6JS438NS0dSzrHIwEc3twMN0=,tag:sI+vGQU+Al+EOtpuCOWHHw==,type:str]
    HARBOR_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:1/thE2mTkKshUy7mrnBS6Bzhs1KmfiTBtFMSnCDTMw7wZLncwkfe2VXL0GVMNpew7iGfHa/M2UhRZAtTe3o=,iv:9bkMoN7qErS+vM1ZpdCHBUxG6CpBOvq4eft3MZRqlG8=,tag:rb8rlXyaUxGoBVchOTHSvw==,type:str]
    CONFIG_OVERWRITE_JSON: ENC[AES256_GCM,data:QUMgkadDClzORcEWeI9JJpIgyDKQ0sMgCyaUF6X7Ki3moUOzWQJMyK1hSOdo5kZ3la1YwrpnpOeePjElMnPPYbVljASwPXyUWNh9afV8moWJdnGr+OGqDfQqivSKZ/+dYgKAQxEpCs1UwZ2nl0Nw8C6Jri/T2GqbAqkManqEs6szzyRY6eA6FYxVdWYMUpgDk2VAQKhU1jipJxkhBYWdLtTitnI8sfMviu2SLUtCdk70vReAoo8uRnUxkIN+Uzjb/9z558l59RcJI4Wz2cG8wlo99Br2eAUT6IIYiJgSukJXBJOXTL5A8uuZFO2yAkCqUSHr53ZzmME+E6FO3hJHefF7BQx9VWevsFoAax8s8WASDfBnf9RGnyCxLO7GKoX5sfnVF+qf4N21KBMb6zaIPBqcl8uxHTKMjIo33W5TEjV1+nK73+WHo0tVUbN12+6ho94f6feZp1jiWByIQ9UiQgft9YXX7NWAduqLMWZFrMeSjNQWV2CJ3dODHRogVEw5v7XxjChtvo3uqjFEWCC6bU82KCiBtDCQqHyVXWDnAx1iraUPdE5+TcysOygnqdzm9KGUIFQOsZRp3uR52CCS+weAsBnzRX/PHFC7XmqJNIlwxvB9WrQPolDz,iv:0RQq0w+P0EnNk9H/S5zIsy/7vLfdH6BFqXtr54sl5ok=,tag:QpYXH3zD8q4U3WHdHSDPig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzT3pJbTJwVU9XSTA4TUJq
            Y2dQay9WYnkzdHlSS3hQODR4WC9LbVp4ekFjCnVGYjhYMkprbTRRem5YOXVxVjhL
            YTBtSUVFZmVlbW5aMU1SQlFBQmV3ZUkKLS0tIGxwdzBWR1BHRXFYdFRnVFEzSFZh
            YzJIckl4NGJpangvcHFIWDl5ZXREZ1UKVscXbiB4G55ourJYeyQ3ACoK+qorNd0o
            dUF1jdll0/L6MFAjMam3rpIc0MS4GSEMS3dac5f6NpdMryLApH9JNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T18:40:52Z"
    mac: ENC[AES256_GCM,data:yiCwRsP67Hespcu9MRCifMJObp60kGW6WaRbrGcu9ZQLESQULdnUfHvndMfwixOuNU3TTcZNvkqhDOvBNU0IL6xqIUl2woH4mzDpbgYc/kDMfqG60610vjzeKHKV0wdkUOcG1F9rK6MXcBPsDy212EBJIXalqxxmtmvECj2SRaE=,iv:uq2xgFy33XEiky+cJzM9gpoB3N8ujqlfIsBXOZp+JcY=,tag:okxWBMM+UzCXtqN8X/jDKA==,type:str]
    version: 3.13.3
