apiVersion: v1
kind: Secret
metadata:
    name: harbor-secrets
    namespace: apps
type: Opaque
stringData:
    HARBOR_ADMIN_PASSWORD: ENC[AES256_GCM,data:HNJA+Dm48neiF9FaEXJzucC+1Ruk9y4Q/iCO0A==,iv:CzrnMirWvmYXhAzYxgj+yidZsLT0pxCadZ/lA0xgSmc=,tag:DPTlTaNtgg15x18GunySCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb1V2S2d3Sk9PWlIySXZh
            bEtXS3VPV21TenFBNHV3a2thMldpMnl6RFhVClNpQ2lGbmpTeXhhT0pHYWFCS051
            c0lRQmZtSVUxaUVqQi9NbFdqZnVDVncKLS0tIGNDSEJyeVhQdFJGRE5DU1BRREh1
            d0FKSkpCWjJLclVReVFCWk9jdUxPdzQKlqG8/StfKW44QdlSbmn6cZPc6XmldfU6
            EGGkgtKmWY0EJV6IBbA0bx8W3LiR/8a6h5VX5FJjc4j3VjpDl06GyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T20:34:46Z"
    mac: ENC[AES256_GCM,data:hJFovj/hL6MJv/pSwtTXGf0nUieUWYCTGM1tAT1EwyX86F3kePYZIHUarA7vx+cnKAhM9mKEI5LLEDnBFvqIJfLJhBrYjPLaN7hOF49CsNmXB4Wn2wj4WKqx2Z3IrEjQWVMGY5RQkXS6LjhI92oQh/X58KjE4VYBWDlE4UwQwfw=,iv:RtbBdLuvK4RUslwe4yvf9YmwHiIYR9MT6UyG2L/fyiE=,tag:9sjbjSYdyV+K+NmKUUWhsg==,type:str]
    version: 3.13.1
