apiVersion: v1
kind: Secret
metadata:
    name: media-auth
    namespace: apps
type: Opaque
stringData:
    PROWLARR_API_KEY: ENC[AES256_GCM,data:4hm0Rr1EJLbfr7P55G/YTjM0DKfYTFMuJ8AIQNTjN0M=,iv:LK8PG37LzZfY2iCPLCargIO0phzeYX7IfXdSPYYfI4g=,tag:4ZGow93yUQqL/uzO7GlYdg==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:RDOLIHTqquDfWi27AcAw1bCmvl6JBJAkojFLm8hN+KQ=,iv:ltnMeYwfQyL4hwwVDpgcJYRp+QmLGYVIMwg6FYyGT+g=,tag:29LO3CiuiC1MhVRk/nHM8w==,type:str]
    JELLYFIN_LOCAL_ADMIN_PASSWORD: ENC[AES256_GCM,data:8VlqZLWatXHXPzmbptY90aM2lttXkm8nmnmfhEicT4lI1Lm88o8BfsI4qa8VRkte,iv:TEustsa1d5RH/GorR4aXFstZUw+z6x7c56GlMoME4u4=,tag:KVjg7bgHQUs+XlPXK3UuNw==,type:str]
    AUTHENTIK_LDAP_BIND_TOKEN: ENC[AES256_GCM,data:yVkpeSNkmzjJ2zh0dfan4FMKUPNhOXwsxvSZd85lcLMKVXOnN/yHPf8Vyziv/meDcfNCrlXoroWUWZj45DYp+Q==,iv:VI3vTLE1GrToSyq47IKeoqdaU5Y8CuVmowqsXtNkLV8=,tag:JdZnXCZdlLgDU+YcOWyAvg==,type:str]
    AUTHENTIK_LDAP_OUTPOST_TOKEN: ENC[AES256_GCM,data:Q8+2xrkodnQvHlVuoQylvnjsg9mS972KzsJnkgMHiEggA8MCKXyljVz01/W1rg2a6y1yd6q1+KYan2dfpaWNaw==,iv:Q82vI3yZZNfNsqjecEdC4ekeutL3+yL6xCSCFv5KQkA=,tag:wTtJ5O7NfOQFSvjaSjJN/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUXJoYk90c1g3eHRmRVlz
            TnJ3cTNHdi9IU2ViYVhMNGhUZ1NNYXkyV1NRCjMvZjN5S2Mra29rSFdTak5QRmY0
            ajh5MWVjeGxiT3BvaFE0cnh0ajA1RkUKLS0tIHhhTFp1Yk5yQ1ExWWJPV0JhNElr
            MFh2RU5WSGlIZW1jM29iN0QraUxVWmMKcBnivpwaifX9EJBnZZkoTyRU8B2lnesA
            2AeZjSId23adzZzZwuivGzensRoNIb/MJKKpNm8qHgRAWiPVLzZ7Nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T21:08:04Z"
    mac: ENC[AES256_GCM,data:lSgaoQQBzRvfGAMZifCFLk9yiOe9X1KGvXMmLUVwD8tli1t5nE2bpwAuAdyh+GORqg0z2/wKSJZhhGAGWkZuCzw9zcHNfvnN5d9Kot6f/Lnsl0VGuO2BHDDBEvLJLoVZxIupk03g2nJmKfV+kFp3+YkRxtb+yHILq+YxfE4EKvE=,iv:Q5TyIhe3Swxy8PyGSukLfevcFSIiDrDdxk9pV9ODJ1o=,tag:4GQY88DJJXJe9Li8o/rdFQ==,type:str]
    version: 3.13.3
