apiVersion: v1
kind: Secret
metadata:
    name: media-auth
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik,media
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik,media
type: Opaque
stringData:
    PROWLARR_API_KEY: ENC[AES256_GCM,data:9ieXWh3FGHW7mrGv1+/fXXVTl501gN0PXZLhrDRafjk=,iv:RGN61VYdaXpzx6cxl2Yb/6FgCIrYxgpHPVOa53Umuf0=,tag:8TANtgLtk9Ldh01pYWF7SQ==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:7ZSK8ZQif3/u7vIlI0O4ce/2WLu8Ey7ybpnmo16voKI=,iv:YpAxKCyaAmKXq73Lbxd3VijgP64X2kq87ZI/iR/KH4U=,tag:HJvMXSxCQ9BaQAddbkL2xw==,type:str]
    JELLYFIN_LOCAL_ADMIN_PASSWORD: ENC[AES256_GCM,data:l+LxdNIKCbE5rLg8XbbQgVtezR5dROMeAUaczB4476Yr0TZJwWctKZbQnYSK+9AM,iv:awYmL+l2/EYoLSBqcKteR19r++MJ5+ODtdjAEaF2aC0=,tag:IgM8kR4zuqMz8bGi2CkSow==,type:str]
    AUTHENTIK_LDAP_BIND_TOKEN: ENC[AES256_GCM,data:SGka3rwXLwz5GVLyKlON4jCblkSEjeBeruGlA3B82Nd/Nh8tJcnFr4fw6cH8NMLNW2M5wzxKJiHyjCyhwLgOfQ==,iv:yG/Hkhk4A/u4SVTuAIPfSZ8+/6bJlxkHsSjUfnPZrpw=,tag:+eIjfQyQP6MsKMgW12yOuw==,type:str]
    AUTHENTIK_LDAP_OUTPOST_TOKEN: ENC[AES256_GCM,data:XkrJ35gcItCAXV0I1wUlfvxEIYcwCcImJYtI7cIgWQfkfggPgHT8P0zu3z0OHvYmH59AO7DJ1zQJaJrkTj0ITA==,iv:JAac7UneiVqnaaojECbuLtPgMdf90dk+QPJRjbAa9rM=,tag:eBP2AlTe+1iupqjawtwK+w==,type:str]
    SEERR_OIDC_CLIENT_ID: ENC[AES256_GCM,data:Z7E5bllTa352rsmk8GVIo78WCgn3KTD8vulT5cbDApVQ37MpROrj7TPRtkH2nXUw,iv:us7bwCysAvX2hZizxc9IO4eksBamCe1WvESJTEke3EY=,tag:gsAVRAGqwHTmYv2/qEsmeQ==,type:str]
    SEERR_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:SMMSaZ2Ohozj3SUe619xl5bI0gtMhqFfvP9+fI1JslrlNuIoUZA6hu/3DlyEX7+Cfs30J4/7TBBjInV7387Gnw==,iv:JCnxgacp0bdzpzyVUtFPl0zdRyMhBVR5rUWMT3/QNRQ=,tag:BL4rjkNQUq5HNHEEKv7Igg==,type:str]
    JELLYFIN_OIDC_CLIENT_ID: ENC[AES256_GCM,data:hHsgzbK0RrkySYWDeIzSrbhenZnX+PVVhzHZH9psFid8vZRQlXuaFCO6cgRrWlwZ,iv:YvLtP1nz3uRra7r/BSRp545pP1WiW6G+c1+Mg4f/Mng=,tag:yWiUYkNEouuCOShhlNKAoA==,type:str]
    JELLYFIN_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:NIRMq21HiuyYaTPsHzfUcuZEWCzuYAv4vVGTZAkIltkFy0GXV8Cjs6JQ1ftljjAeBadbYkF0ev9T/UkoAf8nog==,iv:dmNNmmQwMRMvc6Kc70EfEZo4Ost73x4uLNRZPjlvtFA=,tag:nuPgFpi1d1hXP0+8i6P89A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVUdNV1NNa1lSeGFIbldH
            Rk0xRG5xd0wycm9wQ1NqTHhBR0hkNzdmc3lNCmdoZ2pzM29wOE01YlNlSVZ6WG9E
            Z3Z2YjVtVVpydnhIVi9NLzhKNkZLcU0KLS0tIGtDUG5yODhubU05NHhGVUtTSDhj
            Rm1sSWpTQ25JRnBLZXdVNlRZMTZvck0KF7TSCrcDtCavhu++O0PuQhHOmlf/hSYm
            Tht8Fl9WWLRvMBAwMJ3d7uH6VhYm+gBO6wdSDWFWsv/vMcVqUPSklw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T14:10:04Z"
    mac: ENC[AES256_GCM,data:YAoz7SgjChN8lEeGXfuViqwziLIPVB0HmDJJLukGLGIE1FOOtZK1t/+GaZaEX95HqLMuuYarvDvaUNBXStu+h3S7TnB53fmJqGy7uSGDXaWm7nvei2b9mSo7E8U7IsFu6JOLIG7mMP6GT6Edv7RI2HnmTDfnVEPeTb7qswPOcHk=,iv:n6YcQvYlsQAR1u6qXCHAK5M0JQ8Uv9q39N0oBtJHFH8=,tag:+pvkXz7rNi2WGhnLtXfSkw==,type:str]
    version: 3.13.3
