apiVersion: v1
kind: Secret
metadata:
    name: media-auth
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: apps,authentik,media
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: apps,authentik,media
type: Opaque
stringData:
    PROWLARR_API_KEY: ENC[AES256_GCM,data:d6yqn3ZEt2sZ65XpTPZ7Z4gpxsGUCCpsjnM06hS+roI=,iv:P5ejGHTgg54/2F+MhyW+1TVDtf9QUUi7I5kle/bHHGc=,tag:tFV5XiQnFgKLkycU+lWWfg==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:DeFWHik/6fX6zzaJh9wM3ZvMo828ecgX64J4NYyagfk=,iv:kyKFtyVdPXSJ14CTcPhdercyvXdOCHp8gB/M1KdxBWc=,tag:vKlHizFd/wI03o0jDWL+/Q==,type:str]
    JELLYFIN_LOCAL_ADMIN_PASSWORD: ENC[AES256_GCM,data:Q+c/P/PMLqzsR2ekPNn4ieeUTfdp2bBMMA3jLfx6Fn0uBOrjpJDatgTyOpVRtn+j,iv:ejn4l8yR2K6bk395X5QfHpBgJ50rhXDHJtiTdGsTKqw=,tag:Iss9BEtg/gyI+fKnTq3Oyg==,type:str]
    AUTHENTIK_LDAP_BIND_TOKEN: ENC[AES256_GCM,data:q+JWTdZJf+Vm0Ni4+lYocMyE0bC99BtIe6wgX8Kv9+d73c6YF2tln1sWNqzJp+eiR+jdCUuhc2j9r9Z9lfNWhQ==,iv:xUbaKkpOmWoap9lJTa37BdQcR32bZo9QeihIL9ymRRQ=,tag:AdzWBm7ycmudydi7jXi2+g==,type:str]
    AUTHENTIK_LDAP_OUTPOST_TOKEN: ENC[AES256_GCM,data:igPeQ/gaf1/DjpYdey0RzLmOBGZmrAv59ksnU0TX68gnI56Tk1mQ9XHCyWBvOM8vDGn4rkcuTe2fsutdeo0zzw==,iv:dMXwG1cd7dUAGu962nKuqA9aywPkVZsejCSzyPIa2uM=,tag:zIDP1C7dyYbgt+G8C4/H1g==,type:str]
    SEERR_OIDC_CLIENT_ID: ENC[AES256_GCM,data:aY3bUZYYaG2YLIjm7LaEPl7rN8e6YiqeGesEO/pHM/N9zr7lnhXUpUOikiLdDW4E,iv:jdus+n0Pvd3Tll9CPN4G5wtZ9DBUsZ5fBOyi1GV1LFM=,tag:VxoaeKkgNLcB8uV/PmJPMA==,type:str]
    SEERR_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:8r2Y7JbSm7XTHLmmBooa1NePEErleE6bV40IYN2gl+3ooLAC9kjE7ABKmR2LGQqB8TLGhXxKzMnj5FLHDTINTQ==,iv:gUT66VqCHOOKfuegVvsPrMnk/TeCYUsh9W74pwsMVK8=,tag:c3GOHKUxFPxiC9b61mCpHQ==,type:str]
    JELLYFIN_OIDC_CLIENT_ID: ENC[AES256_GCM,data:tldZlRhMgk6Lxk45dConzvBOym1Ed/lo15gBVcShJJa7IrPe0svNj28y8+1qztVk,iv:SLzCeefFwzXfFwIHURG3SGtkx+buI6V7Kr8ROgeYo/Y=,tag:iJ/qKgyqcqTPnzPsuT7YpA==,type:str]
    JELLYFIN_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:5rFDsMPtNdJxqjC1L0/FITFXdD/KDmmuMV96qvJE0Eqnyr9SaX6eQXOW8JHpeckzAVNbmerYN3wL6shvUxvfCA==,iv:WoRyOCV8879w/E5h0/V1mzal0SqLy93D7lZiVgYwuIA=,tag:897DINzC15hNv7H+SQNUmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVERzbzBMczJLZDYvcVpM
            cXVVRWxzMFNJODdpYUt2ZTRjemZJd2FMakZnCmFYakNxa1A3eEErM3JuOURqZS9O
            NzcyZWlkTXZkY1JueFZGYnlibkVjZXcKLS0tIHlnNndpalVzRUFOaUwvVjhrREgz
            NXViVkNSaXRTUTNxc0ExQ3UwZzB3MzQKGh4ik3skQDU9C6MVFc8SnYLx3VZQNjim
            kESb1rilcFV0kstWPUTijYs5vWTT5/zxzLuYDa0WwmyLOZ8U0GrvMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T00:05:59Z"
    mac: ENC[AES256_GCM,data:biPMrwk0aLBaczlbT7kYUfeojBD7ZbAyBN6/+Hw74bJT80ieVSXH+Z4dXGjL4d/Kj9acqlQ16KzmvYLTtP4It9rljyEuEsJbYYCOtEZBN6q0zOV0uqAFoKINCGfzzeYI0NuwZ58PgzeFlAScgJiVSzWcxSWN0hCj3esDE0n5D20=,iv:txcAEBTc05d3tj/n/KbVTyX/iRiUfIrDnvxVfqOgAQk=,tag:CAHvC1iuODiPGYZ+acAdKA==,type:str]
    version: 3.13.3
