apiVersion: v1
kind: Secret
metadata:
    name: mlflow-postgres
    namespace: apps
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:yc7gyLj+,iv:PSXD0odoQjQgc/xkvbcOIVpUZJdQS/Fd7YfbV/B0hf8=,tag:FvrEZ1lKwZYeSIN3KXbkTQ==,type:str]
    password: ENC[AES256_GCM,data:erEXNCGdWQexkUUWzS7lxe7Vi7iAJJZTs7HScF2gKf1M4hf1Gngs0A==,iv:4II6IX3S4Y7fvZsqw5o79eYK+hjR1wSIseq/EPomutI=,tag:r89jF7pr/ZRAGYAFa2/baw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSakgvdGEyMGp0dTEzRUJo
            VzdmWHd4aSt1cWFrTk9rK0xGd2xvNEFJSTNrClJMVzZNT1htaGdadnJIMXFCQ3ln
            dmlYSzRCbitWeFFkNmloOVlaZjBmV0UKLS0tIDhCbGs2OUpzcDFNV2FPdXBjbjg3
            VmppbE9UYkxBMWtZWEk3ZDZ4R0l6NGcK/l2QVBxk8/CBiv1tdPBElFdMtpGYRznq
            zbGbnBhiwjf3aANyLv4P8WSTS2O7hmyl47g+/YecO4DKmhUJnSCkYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T22:09:40Z"
    mac: ENC[AES256_GCM,data:BNrn+Sof0eFKp5nSb3Ot7+Dpk5yZ3NigtWTvVyN19P3fjDD83qm6H2YkmCVVB2EmlkH0KKM+kHWI0zv6P6g6wRTYh/FdjtUYE+QJjBznDGWZjxZ7ap/ymmepzcvBvZtAw5f33fRHHKndP+IlO0gG2H3jaycLJ4BMI0lRgO/AazI=,iv:4bQm8s/FlIgtRhgoqBQg5IhlwSNPbsdCah599M9P/Gk=,tag:oaJWn9u3tB7kX6+cS95zeA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: mlflow-oidc
    namespace: apps
type: Opaque
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:HEPaSg9sTybfF97g7XOb3JQ105+8aenjquqv3x4zEvedqoyaLd3N60aHttatGp3tBFya8ZEwxIocJOwS5dbOwg==,iv:QtqM078WkioZUhBhd1G/OvnNRwMrGtPzNUVKO3MX5bU=,tag:Il9A1YQonpj8/jvCcYx3uQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSakgvdGEyMGp0dTEzRUJo
            VzdmWHd4aSt1cWFrTk9rK0xGd2xvNEFJSTNrClJMVzZNT1htaGdadnJIMXFCQ3ln
            dmlYSzRCbitWeFFkNmloOVlaZjBmV0UKLS0tIDhCbGs2OUpzcDFNV2FPdXBjbjg3
            VmppbE9UYkxBMWtZWEk3ZDZ4R0l6NGcK/l2QVBxk8/CBiv1tdPBElFdMtpGYRznq
            zbGbnBhiwjf3aANyLv4P8WSTS2O7hmyl47g+/YecO4DKmhUJnSCkYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T22:09:40Z"
    mac: ENC[AES256_GCM,data:BNrn+Sof0eFKp5nSb3Ot7+Dpk5yZ3NigtWTvVyN19P3fjDD83qm6H2YkmCVVB2EmlkH0KKM+kHWI0zv6P6g6wRTYh/FdjtUYE+QJjBznDGWZjxZ7ap/ymmepzcvBvZtAw5f33fRHHKndP+IlO0gG2H3jaycLJ4BMI0lRgO/AazI=,iv:4bQm8s/FlIgtRhgoqBQg5IhlwSNPbsdCah599M9P/Gk=,tag:oaJWn9u3tB7kX6+cS95zeA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: mlflow-s3
    namespace: apps
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:OzJcOny77TlnNg/BS+LDbCLfM00AMX8=,iv:IoZo4rVjfwXJI/V/AuXQTRO6eIywDLEaPaO9gvG/NrU=,tag:sHoqLkWyExdT5ExcQHeaJQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ggx8O6U1sN0uWGDKpsthfjoY2lN7yMQN5xrRiXR3qMP7/AKdCfR92WoeIAdya5aP,iv:N8i4bK8RPAaa4ug+/eSpsmlZ3JDOwU92wwhGlQ8n658=,tag:FhKf5Dtn1xhfvx0HAv0bHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSakgvdGEyMGp0dTEzRUJo
            VzdmWHd4aSt1cWFrTk9rK0xGd2xvNEFJSTNrClJMVzZNT1htaGdadnJIMXFCQ3ln
            dmlYSzRCbitWeFFkNmloOVlaZjBmV0UKLS0tIDhCbGs2OUpzcDFNV2FPdXBjbjg3
            VmppbE9UYkxBMWtZWEk3ZDZ4R0l6NGcK/l2QVBxk8/CBiv1tdPBElFdMtpGYRznq
            zbGbnBhiwjf3aANyLv4P8WSTS2O7hmyl47g+/YecO4DKmhUJnSCkYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T22:09:40Z"
    mac: ENC[AES256_GCM,data:BNrn+Sof0eFKp5nSb3Ot7+Dpk5yZ3NigtWTvVyN19P3fjDD83qm6H2YkmCVVB2EmlkH0KKM+kHWI0zv6P6g6wRTYh/FdjtUYE+QJjBznDGWZjxZ7ap/ymmepzcvBvZtAw5f33fRHHKndP+IlO0gG2H3jaycLJ4BMI0lRgO/AazI=,iv:4bQm8s/FlIgtRhgoqBQg5IhlwSNPbsdCah599M9P/Gk=,tag:oaJWn9u3tB7kX6+cS95zeA==,type:str]
    version: 3.13.3
