apiVersion: v1
kind: Secret
metadata:
    name: mlflow-oidc
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: authentik,mlflow
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: authentik,mlflow
type: Opaque
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:ymHrWDE3ZWGzIagwTICe+zsRCrxRXEGn+yzSZ49p/SaWW6opOtys3wV55RakSwaxvtceBKnVVqUXs/zbJBJc/g==,iv:cPCp9A4S3RUVIclnQHGOhD9P7LIrpT2yqnAcUP5fDms=,tag:4s5Ye5ZV/aLMxVwXT14Tzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTEtXOTBqcnlnQ3IwVmZR
            WWpWc1VEalN2Sk9veWhRb1ZWTjZFWUFIRm04CjdnZW5XOE1WL0pqWGRqa1NwUFpk
            eWdHSUhkaTlNTEg2eDlCK3VkRjRLU0kKLS0tIEc2aFZXZ0c0Qlo2VUFUNWlORXI0
            NGtZRFhmcEtHQmdObllRNDk3ZmpSRzAKTe1GcP9L7trs3jbpxyizQf+uCpT5/lzV
            OHhl4A9d4HHS6cVqUvdjZM5wEIQmOt1il8wnh9hPu6oTPtTteV/JWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T14:10:04Z"
    mac: ENC[AES256_GCM,data:nU3ifSRXz2rDMzOq0MKQ2PIvpvlurvk3giMTmZdSHtldV0V1A0/omt5ZfZZNqEeLPtCbO7Qt1Kutj4pgFGCFMkeW/AP9SgqbO+CgznfeOxdvU/xjiWU1zdu8mBVeGTVPP4VRVEWasu+rgs+oadcQIkNcWZ4Fdy2JtSSHsD6yeEg=,iv:rqArPFAWJOljI2aV0aoGr7rikJFrDevceTsILrP8EOM=,tag:cxJdsgCA+YSkDey5mVf+LA==,type:str]
    version: 3.13.3
