apiVersion: v1
kind: Secret
metadata:
    name: mlflow-oidc
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: apps,authentik,mlflow
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: apps,authentik,mlflow
type: Opaque
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:8hdx4mO2PRoV9fTALsldxxA1+lOk2AE+kIrwqP63b31EtXDcC59Aku3LjnQVd81IOOcNSI73aIFYJ+zxiwRzmw==,iv:xKhQMYyLunv1W272RDQqxDLoZHSZrV9tAugcI443/jc=,tag:FtnLkujhkOLNAb3iy3TgGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNFpCTkRRbkxxS3E3MnFM
            YUlMb01NT1ora1Y2V0dlN3RiUkpXMDRPZEJjCktTVWROeXBBYmFyYUhZcnZhS0tk
            THFTcDhXc0p2cFRaUVdCakFkWXdkTncKLS0tIDlZU2xzamwvZDNRejhuQ1ZEUkNR
            YlludmsrVTNkd1NGakZXVTJMMVNQalUKQ7YuEoyQrQGg8BtCM3Uih+236zNRNrFK
            QOVFNo4NaswvFWoDSZ3lgSlPD79wME2M8MH9R535NcSX81yUgHnFZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T23:23:10Z"
    mac: ENC[AES256_GCM,data:2zNgnE1sCzP3h6qU5y5C379k6pxnnxGBqA7AP8QkU5yct9uolLbpI5sn0UPay+1rr2mzEIIXVQ0epFYu18UJ4nD8I9kLzS3e+APv8IeILvDbBfxL5NrZXhuQu0QeNeGohJ/0JrtiBbpWU7Zel6a6626J/Q2fugmtwUTGKD0iN1w=,iv:TMZFo43UhrnAXX3HvwngzwrEbDjLqAf7uGOa25M1NlI=,tag:gi05VurzFC4oVv6HxOsAwg==,type:str]
    version: 3.13.3
