apiVersion: v1
kind: Secret
metadata:
    name: odysseus-searxng-settings
    namespace: apps
type: Opaque
stringData:
    settings.yml: ENC[AES256_GCM,data:hZRBky+EM6IJZYfabduld5QD15lFqcM/Pi94VCY4sfZqh0Y6bHEDkkcNgzDG23TSccJ3SGXqhBoohitYb2ZoJjOgjfO1IsiQYMMCQlbElFxeebasdVQmILgxHp+rUpTy9Bj29/gLs2XeaDiLMPI1ZsRpyl4ToIkmwSFKut7ZPzTsZuZG2ldCydHvHqqSTCIwVFA0RybctslfEoRELA==,iv:4SnJgCx24KwLB4omFVHwwf0NyPJH2zZzSVCluXzr7ZM=,tag:uVPL/d8MrDZW7jNWmIzzIw==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSjZQaS9maVdrWERoZ2NC
            Y24ybk1Id0d3bEtYRHFCdy9KcnVWK3JESDJFCnJGVmJnS25CYVMvSWlEWVF3MXhp
            aklNT2VMQ2dkMDBuTFdvdGdSTkZyd00KLS0tIFp2MU1MOGRCKzhDNmNvdEhrK3hp
            REdoR0s1YjhuV2J3VG95ZW1Ud2VTbUkKyAT/JNPB4CCgcEJfDPEPHHz4cBxWtjZn
            NSoc82CaZ88XnRTf1L4DHrtKaDMwBhfL4AHsGVlj4z79kTFyU9JkmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T21:38:53Z"
    mac: ENC[AES256_GCM,data:zWOqFuJXr7ukv+y3USAjFbQaAeR3S4I79LYPtO90hsFRH2pfZeaspy4jZj5KXmnv4WQcY2LY62kkM1FoRVsxiGE53YKcGvET5Yc4G097Ll7kyMiDO9blMxQ8Y3dL/BLi9D5nbxF+MDl+msB+XmZ5QpypLMEzj94UavaUP+Pd6BI=,iv:RGBAFciGF3dZFt1LB+hpAxiEiDUjQQIeXtUN9PofA/c=,tag:LxTf4368SzdaV3vuLLKIdg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
