apiVersion: v1
kind: Secret
metadata:
    name: omni-backup-s3-creds
    namespace: apps
type: Opaque
stringData:
    #ENC[AES256_GCM,data:4piyhPRiu2VjYStgPM8xuthe02KZ7W3hgJ+qfWagvFrvLl2I42TGDS/s8dYhIlcZ4UIyupUJc++wy+4z18sw5L/2RDCpsZZW8jle,iv:O11Ve9MkUDEu4Va+a96UwjT4Y8456i8Cce9+9WY2rsQ=,tag:zWTRNzecAPZ1BKySGA6mQg==,type:comment]
    #ENC[AES256_GCM,data:PKkHhVaPTqn6mZnaFSqLKr11+escX0znp1TwWCGb2b87YlBQmVRnShoXuRyc5UZi9oFdvdx9WG0w3+XTs7cPZGSb,iv:ZjeORBsY/lFDYrMgEqIcKUYMJ6p06STfUOCKjbh7aG0=,tag:zNq5NA+h5kCf4S7YLiJXDA==,type:comment]
    #ENC[AES256_GCM,data:YPeLnHdXzfafbiO6pyZXfLf5EnHc0mzQ5ixT9sNilzdo8mbSfUxtviHRXBfgqt3epjtbpr9HwnmufdA5fIifej96g5TtlPZn,iv:dDB87IAz4SbG/uEphsbNAXOxBLbiM8Syh4GgaWTaf4U=,tag:ojh5eM/MgxIS34WxbGDZMA==,type:comment]
    accessKey: ENC[AES256_GCM,data:+bQmzk3F8PkpL7honMd/v+EU6LrwdF6q,iv:GE6xzpSPKDJyrM8r+/8ebXOFDBa8Yo6MBW56qjZ63PA=,tag:5XHBiT75Xwv/7FuWBfNziA==,type:str]
    secretKey: ENC[AES256_GCM,data:cUxUWT02n3qquFIYPBfPOzqLc7GfnFKxIcm4plLWO+OzJ6oLoMUt,iv:NaipkfQWVwX/FC+MGiJoPfu3k3mZK0rMdllfcqhpd3c=,tag:b+RsZPlcHT/GAow2qGqEuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFS1FlSlEvUWJ2OWd4WUcy
            ZGFJQ01melkySG1LL09DbWdCbXUyRDFYSG44CmtzZUpBaUIzK2Fjc2RXOE9CM0w0
            ZnBEOWdzZ210V25aSGtYd05ZdmNNbW8KLS0tIHo3TUxWVjFlVExvc0lxakJLbDB6
            NkVmOGR3eXlJd09zdDFNMEp5eFJHd3MK4d/VBE6KQbJlPUxEOV98GkntkPJxq1L4
            rhCzxVW5AqKHTcv+aiAO9KIzSj10lkyg76O/sWQwbLcZWkkHCJENbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T15:51:39Z"
    mac: ENC[AES256_GCM,data:bxzLzcodDEP5/pZH/yAcPLQs+TrIrNitf8OPwezQLo0wnZjDhRJihzr3W7rrUTzMTedEfickYG1b012b+CT4EWwJNlcIVXNI1w+dFWOtQFa46Utn6Y0eLRHEoXS+jHNo+/8hKAu57+3e/6A6eTxMSqAkXcvYI9sgWs2g1GkYDOk=,iv:AnfVa3ei5sY7aSnkaYaRjQfZ/DRSB5wyV2V2SmnAwA0=,tag:WjZMXBbLbzv+9RFrLvSTmQ==,type:str]
    version: 3.13.3
