apiVersion: v1
kind: Secret
metadata:
    name: openvitae-secrets
    namespace: apps
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ylT2sjfuJZkjqtHQL/Ht/OZBSrUbi6JsKbvi+Snjt56N/SwQ6KjvwMnS4/ln6spKeFZEYJ8WI8ipn45SryvpcXwOA2IyutQulKE=,iv:PR4fZKPBY/pogKwHFqyfn0FleVWIDBmMrD9yow6mUgQ=,tag:1eRmrVLLtjJf+9+0sqluTQ==,type:comment]
    jwtSecret: ENC[AES256_GCM,data:TPD2CjUiJael1DJYFghY+RBRWs31Awdz6ySI5US7uU6WMXBtLeUqP+71jH0Pm/0UAsnn70Apj6AwzT+1QuPvnA==,iv:tP58R1+l14gm/R+C1XGH/ISM9PdiWTgbrogMR7xUWoc=,tag:82bCTzjb08unR6zXfXXKoQ==,type:str]
    adminPassword: ENC[AES256_GCM,data:XziJfLCDLm7LGg==,iv:XoBWfGeukbjtI5m/lxi9R8+zC39q90ZT4OBSjo8wTug=,tag:r6KWkYQYAGgBa0I400RG7A==,type:str]
    postgresPassword: ENC[AES256_GCM,data:VBKlDWw7PxBj7GhfanMhHeEhY3Po69m7a8F/Yo0xpm8=,iv:82SbLxG719BKXrbZbezly1nIrPm+7+Xt9CVOPvsf33o=,tag:+8pjg3DXbzC1ccrOUSxTSA==,type:str]
    minioRootPassword: ENC[AES256_GCM,data:vB+lPOB/CCXk3KAyWLR3PkcS/pBYOMBuQl3ayDVPwyQ=,iv:oeFnyDomnrSjlnot6TyEsxoP7HTGaaZmnzzSjEoBqew=,tag:gelhgEhDL5mSNw8JNqIzGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBK2pkTW80dk9EdVRHM2xJ
            K0luRnBMYUZpSFN3OXZpZnNhVWFUbkN2eXpJCk5NSHFsalFkMGY4QlNrZDd5QlNJ
            bzZ6VjFKb05TVmxNWXQwRUI2YmFiQVUKLS0tIE90cHRJcEc2cnhweEwwWmtvOVFy
            bXRybGttcXM2RUF6THZ4TVd2SG1ZeXMKFXciapLSD+MR1/9WFGtV8y6LoiPmRVid
            mfL5GCMBVQ2dKqdcd4gJ/qLtdZTR+P+Nmejt9EkVwIBJ1zU9bZZpFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T00:18:06Z"
    mac: ENC[AES256_GCM,data:kg+a2AwxiZico8ByslqGB0aw51dDrJxDCwibP3gVTHhv24cBVL4n48ZbUukD3FH59FG8YBR+YaYeVBmTah+fnIBUuIm3c8KaK6YMVtP1jjeR7qcCUbGVstegD3p4EWd6Ozx71ImV9tK47FmHc1/s8fV5rfWr9yC2pljIZwVovpA=,iv:m28b0BBSDT1lsgHI1J+BXYI8Y1U+2sQUWj4tMeJ7jXY=,tag:pp1cFtgrIVdBZTv8vPDG9Q==,type:str]
    version: 3.13.1
