apiVersion: v1
kind: Secret
metadata:
    name: openwebui-oidc
    namespace: apps
type: Opaque
stringData:
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:yEcDTZ/yJhKHWrjISK4Uf1DyuY9YEOPX9vJ1MX1trZQ9aiD/s4zW54F7zNiWuZnX,iv:q6PGU6g8Gs2o8KcAaR4onLP6XP776D+m++iej1+hwP4=,tag:ODQr71Fp9cLFwQlAHWrFog==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NTVHVERSdjRpcUFGTlFL
            NDFYZWtQK0xoVFU5N3EwQmRvZFpTdnhyOUJRCnZKcWhrMUR2Z1hnbitCdXhxY0Zu
            S0V3Z3pVdUwreTJiNHpOcmZZN2t1bEUKLS0tIDZqUjJGR2lwUEcwcmpaeTFmWlk4
            VVE4a3l1Wm5YVFQ1WTM0dUVOR3JLVHcKT8sod1a7T+ZpktW76DsSJXL3jH8Egp8N
            Ac2AKdcfzoD6+BDGR3LTRH8hNWXIOv9TZUo8wGFit1gx0n9npVW3vA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T05:33:30Z"
    mac: ENC[AES256_GCM,data:+H/4gMf5rc/JwhaqagNJN1O5uhAm2CH9hob59T2xjKx3bwstGqZL1ZE/dn4mu0wy4Xf1epOJW7czpjCOA0EcXilRzHNjCacydp9Mg85ImLnRPn+YYINkzKDCY9N5AUGR/1H7IWWgZNTm7Rj6wPP4aThq+euTPIAZ5xrbuPVsKw0=,iv:oipD+me3Bt3ifoGrFGZ8AoIMF0BqjXfnmU5BjR+i+IY=,tag:t3e5TEI1FxoNad9TVXrYrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
