apiVersion: v1
kind: Secret
metadata:
    name: paperless-oidc
    namespace: apps
type: Opaque
stringData:
    PAPERLESS_APPS: ENC[AES256_GCM,data:/w5ZdjO3OVpOPSb8+Nefwcl91C7e+1p+81Vjl8wh48oOkV+UTexOhyVoLMkG+Q==,iv:Ihy9dGD3HG8TuWt36QyG16FgHr14aNSvRnwAIj6NlTc=,tag:r5xdzC+Mn91S3GLa7CHvjg==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:EvCRxjEDVb0LEOVUeh95uApyg5NWWF0UNBnz/mkpBRdvKozZX8tsQ2fjHKRNXpNHB8wPl71JvBLL0uYlNXLUu2zbaP3s1jq78+jB9rhGGYrrn+XmlndgrftDWm/VbD8JUVMhHhBtQPVhXUDKzYmAoAXUmMNU+Xqy4Cnd83R/d2KXQpukxK3G+iOLiwbOy3F4ulsbD3WEpZq4JUMvrekcyxirzsWfxzxhJdNkROBr1PV2U7uGT34IplDC/KqwDy2JKTwXvoL/mKnMlTx7CbiufH99QL2DQOP+2Rw2vqQ4qyC4uRab5uRrm8vQlaiFAm258yMZJKuIB6v2BwmiLqpK12OqnnECULZP+sUI1eqG5zl8UFTt61c4t6wzhBeTdCKD6hJAZvcVCJuEGqm2vnAKeG7xmrqUj8WuaBTZrXY=,iv:cf2r35JmdzKUa/YMhRZ9bzP81P375I43/RnMpgzkXB0=,tag:rhb/1YGBoUsZRKzasDc/7A==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZVpCTGNEVWJDM3FBdHUr
            d0t3YTJ4bS9aUHhpbEh1OHVVak0yVVp6YlJBClNDM2ZhQVVHb1dWMGxKcGNETldr
            dXo0b2piK0EzZ3hKaGNRTUF6U3p4NU0KLS0tIGNlb1UvN3FORERQeUFHRmR5b2FH
            NDhYSXJ5QVZGYnhKTWsySlR2WG9WRTAK3UpyRi0FAIEqWNp0oVfxn4SsjVy+DfDB
            ApnBLAO/DpcGvXj8VTB/XK4Awfv2COIe/7Jl36B0qwaX6wH6AeJTUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T05:33:30Z"
    mac: ENC[AES256_GCM,data:5tL6a5NwYC2NdhVT/uLIrUl8PJ/uM5PqmOl1Eaa0TLXeITqipYyC9nhZ0d62aiCMrXyA5cCq+iuXu61q0Yqn9mD5ZvrUtxjvTdrbQX7BK9mZclnqXKBYbt1vl0BYnWDDtQXVgcURZ6pLsxrsupre7Np2grqfbAMbwPkXHyET5s0=,iv:gAKmxDpRNl40W1aiqG0i9UmKys9FEM2xGG2wXpJRV2c=,tag:rU989P7OgSToye20lut5CQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
