apiVersion: v1
kind: Secret
metadata:
    name: paperless-values
    namespace: apps
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:KBrJHblmHyGN+YI4VH5p/+TtTVOE4e3fqLqzkw6nNwzz3KYhyertUhcwrJWgRBTtxdagHSuXQjBMmyiN1jFrULJ6zyUYUAFRpcRstKftKX74+FgKTsqmxI5bMfHNQWLjG1BqW0CBMF+HaXlCbi+dA58+W4S3NHmVZ/e0NefSmlfRABDklr0fMZ0N5E90X2t5p+3a+hYpp5U4WNLGzxYszm26/0mEnBG7IBQgEUXyu+m8K1vJBM9IXfzxvtGS8ubW/L8usV7ZOGAQa9TTJorwyV+upbfo57JPf/y5l4qWiV04FxlBp0mvRqVNiw0s44EOPbnA6cDUQjMtZlbgILJ1H4VXWC0uonu6TuynEiM1P1ZWw33a2gK8gKvjUKwuStEjtRTBw4mSbcTiLxMjeDB+tn1Zul7b3dXhoFUCCjlibjBGg2gCoj7F4RtDZ9o+xSOqpF0EItRvgzEk5aS1HzgCWppY4UQRAuPFMMCenPVVKPA1rzQ=,iv:gRHcztG6c9ERlxtJNDXz5fY6BUY9MsPXOeS+7wCTLcI=,tag:rYBbaXfTn6inqOSKRDnm8Q==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRHVBbm1EajdYSmlud3Zp
            SkR2d2ZiU3NoRkk2M3lpUXlKKzMzUHc5S1ZNClM1bEEyRDhvRzlGbHVLR0xuQkxZ
            VG1sMGZuKzVlWTNkeDdxd21QNHJDSzgKLS0tIHUwYmZaRm8zRk5OcTJIQjMwSEkw
            K3l5RHJYZ2pTeDJuYTBtckV5Y3RTTzgKXL5v76okrtzd42y0K547fhDK2DlxXNRX
            2P/dYUUOFXBGHZZVoggUvzMzQsNDcyluJGGBlokpxICCl6I8vhLQMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T03:50:35Z"
    mac: ENC[AES256_GCM,data:F4v72EmxG6UFKtZ59lD/1jDWLjlBmkg8x9YzFXJMo+wL4/mcKGyhM9k8Ce11DfrZO4i2GRC5aGy3i6kh3a0+SpSth/x/rY/4rZoImqeGuLr/O2lwbUOUxx6jxEj241CUgCu6PwoO4DXwuKZpyHTqigRoSz9y05LE2b9pFRrLyUM=,iv:uJ6XkbMwzDEYRMUqEAQ9TsAd0nIMryC3lyNToGMbZ8M=,tag:xIR3kKbG+ZZb3lfmujuRbQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
