apiVersion: v1
kind: Secret
metadata:
    name: paperless-values
    namespace: apps
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:1myh6QdjyUi0dZ/bQh8tRfQNM+b0lhdO8NWwORRsDxM4YENSAw1YmkSBMUK9mqCP7jmLE3uGtDfRvJOlSWnixR0dRKDoh4o5TsSibHFnk3m4HMpI9KTGT81L91NoqQPAOU2HPGiC3eQ1KJhJyKXic+BhrGJNwfmyspe04Fd7Nl3fA1P8aVlP9H+qXyU9rAfrpjqZHUFJXl1054Yf6klOrwDo0s33Er6iWfvtMK17yqrlR3qVJ3yE62hRt+PawPWLGWm2cFr8JPPTDN2gPZ1kxJG45PWLAebJfhlLxUPBaGEmWgEZvfDSa3htNRzf4hYRNyPcSQ37dxnAEm/LJWYpVkzgNTj0LZwbo8SNSHxz+uYV4oHkcmPyfQzfdFw+39wnioI1oOnEanfRg6bQhLqhmy0UieMREFwd6818P6+5JfCxpzdQ4MtLqxc/kbp3gKmQ9o9CoFB8PEGbbOhf48op8qKIY1HdFfWkcCwFqTehOLtxHna3EqMdAAlE8Ig3vlSOrEscSsOybF0/XNHU+qQtEm/CvxGiqmWKH6R8CGRsIwWgnEziWW+JOZfFWexMZUv8SxK6uvmECdCgRnElb3UlWLn5kl2ugVhXEg==,iv:/Tq2l847AAVkfZqq4qZaVXE9QI7ngyTuOO42oAwBPxY=,tag:aip642ZN2wHOUtGw05M03A==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWHd1dS9ZcWlZOGxrM3hT
            NGNGR1VUT1QyTUIwNmNVbFdsbDg4MHhLMUE0CjFuc0NCVnMwenZBdDBxUDFxeExk
            eUUxQ0hCcVpyckd0RGRIZzBaSWpLRTgKLS0tIE90VTdtNmlWc1I4QWNEZUh5MEly
            MUFUVGlpZHJ3QlJYaU8zeG1zWEtqbUkKtavYjnJ79axvn6xKXhgZL0cvdfArsxbX
            ucmUHP743nDq58IdbugaTT1HzG3Hf6wejSOgh9rLBaanlNeNtPhqCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T04:05:59Z"
    mac: ENC[AES256_GCM,data:ezoSoSoFq22Y1IloP36XM2wYTCqlp8B6Q7X5+L2j+AhYSi402zClFQX4cjXS1mSJvnLsUp4h8UTUE0TwSithBI39Tr/bXzW0Q8kpQ5/LjHy0069EUHQWpzS7svM3t4vTxffgz5E+vwvcm+m16AOvQ6F484gyWR6gTssnKpMehno=,iv:nJVNs1cfx3d2nRB/whS3997b4aaI0m46Aax29I7pJ8s=,tag:JUDmO3OwmsPKajfaNINcAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
