apiVersion: v1
kind: Secret
metadata:
    name: pigeon-relay-apns
    namespace: apps
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: pigeon
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: pigeon
type: Opaque
stringData:
    PIGEON_APNS_TEAM_ID: ENC[AES256_GCM,data:ckjSvV50yeTvDQ==,iv:aZD3+cCgJRH2OxX0/RdRIbYGpXBqfEwR4MaeNv7H7Z8=,tag:YeYjqTWdZBrVZKSoaOlumg==,type:str]
    PIGEON_APNS_KEY_ID: ENC[AES256_GCM,data:amNCTusBMuoUMw==,iv:UP/S3oc6Bau6UiFVaSBLNzhJUa4I/WEhyYF0UJBa234=,tag:y6w6Jc+SdsEZEYoCDgZaww==,type:str]
    PIGEON_APNS_TOPIC: ENC[AES256_GCM,data:eF0P41qnSSZulTz3vmSoTN4xWquZtRqRM30=,iv:Dv0FyWGVDLTVGuvUHMz78HsboYQH0Hqg3QSxhNL/SBc=,tag:Bn1CbEEZa6UmLz9L5BOU/Q==,type:str]
    PIGEON_APNS_HOST: ENC[AES256_GCM,data:K2gpe49de7VGEacFXQPnDpRv,iv:aPDL/AmzTdJa9l70v/HJ5vFfb5PsZMDzR172wP0WXYk=,tag:YU2rhaacjH6boMN6jYR1Rw==,type:str]
    PIGEON_APNS_KEY_PEM: ENC[AES256_GCM,data:uADD+HI/STqRFLI6FG/uguo69TCDbMtujNRanIDKwOzU4DncBAq83wO6T7vlzZ79lTnyUqbsgWllkroL/ffuAZRJ62wTicsl1UI1vLohDkBFdMe6OySqRBc4mSRTAU+I6DAKgYpKHekM9x0t1e4PAsgilNhWkI2TfH+AUbXYomT1iiNJMArcE1Clu0tGjIIzP3/RBEuRs1uepqC893HxmQ6YZ7xnPZVCm0GC0CKptetQKdfpdeW8iH/wGsd5wEbYj6amjNjAdBoPqNkJ6vOXnDf7rLyxvA3rpas8Qa1c2FY/0c2jVqHVyvuDX6rT2YrnLpX/DWhjJvRBVBnv1WZDX6Nj,iv:xC7f/V/BZQtzGtNNkj7gn22rzREnfYA/IqEQA0cMRcw=,tag:p4E8YUZqml1n9kL9wQst9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTd2IrY2YyNjRNQ3RPZVpU
            MmIzMzd1eU4wS3FNN3RCUFlpRkJSbS9Ra2hvCmw5OXJPaUczS09VWm5oa094VjVW
            WlFWWGsrYzY4MGNZZEo2dkpvRkh2YWMKLS0tIHBCcGs0TW01ZGRnRnZRZTJhVlNU
            aFg0ZEhVc1FidzRnSk1ZVHBRTDcrVU0KPrD0P2gJDtHCjGBuHcJuiKTTSPQVPjn1
            qwqCp8iLdQqis3mrmuezNGgODc9jWQi3/Br0Hw8K/nEdVUh/0QdpVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T21:48:54Z"
    mac: ENC[AES256_GCM,data:Ax3g7KcPJOb9YvE5m+JuVTrSdaFxgAZAXMhoWAaYHRDrkL2hXxYjlYLnb9mv3s+EeMLi8HlbIjlbCxrC46GC5LVpgJzQ4VcnBG+S1Bz3JrHL4rExaEQJH/SUlDQmGME61zRqsC+HfZgFbGYeWeD9FlGyXinGK/mb8O3xeXpAOA8=,iv:klgzTdVor9p2nFWelt+hdp5n4D7kEi0NLGnkPcQvyEo=,tag:z4zaH8dVYioPirGfR+ijMQ==,type:str]
    version: 3.13.3
