apiVersion: v1
kind: Secret
metadata:
    name: pigeon-relay-apns
    namespace: apps
type: Opaque
stringData:
    PIGEON_APNS_TEAM_ID: ENC[AES256_GCM,data:+KMuJ4mHM6GUJw==,iv:iMrfVCLiUqe+I7yFHYc8RIqFOdZnGDHKvYSFr3jWF/0=,tag:tHv0PbgszTKrH+labA1Krw==,type:str]
    PIGEON_APNS_KEY_ID: ENC[AES256_GCM,data:9Aw92tzsPOSj9w==,iv:6aFO/fcMSr+C6dbi6QPKqOh0FxgNPpuS8z9tlgDlFHk=,tag:8qTklHGNErSTNe6+Ox9PMg==,type:str]
    PIGEON_APNS_TOPIC: ENC[AES256_GCM,data:ClmFn0QV0zfytNDbgcGukNEL9nYAjWbc1yc=,iv:L1RwmZ2IsyUKm5VYbB7x+pKYF/UjYY38xsumCV07yJA=,tag:bbzPOHYA3G/QhvtDXgMQDQ==,type:str]
    PIGEON_APNS_HOST: ENC[AES256_GCM,data:xzrIFDQDQ0RE93WoloKibN22,iv:VEyLiwXNK6xPZ8pscKlXLeW0VNVyvoXpIAL7tGknsuA=,tag:sVfnf2VE61/j+8bqZEVg1g==,type:str]
    PIGEON_APNS_KEY_PEM: ENC[AES256_GCM,data:i6EK3lkPVc3zpeyn59tShSw1u2IsQkymKH2S3ceL7KaOePvqOle+SF3BXkNUsNjYl1NSVJ90IalBfVFqp+jxmajZIEYTRocach33+uQnEiXloLCLeJaVPyUKtHE/zC6LIGYHQiJIotWsifKfk8A1vdNjPI+euApRBLf35DIrG8mhPqvmmtvwNZ7l3ax2qs3LmcJYTu7UeksqGr3buaSj1Amvmp5iKi58FOyEX4NuqtWaqKWatLkMovWl1WxB5RqXHRw3qQiuBtsSMjQsbR5UqCZsd/EhAmbvsxv7T/t2VCLDQLW6gGbAA1cvSeYhv2/LIxvr2VjskKJwwc8goWYEra4m,iv:rFxj3qCLkpUtPv2W7z5GKmTMmrocdYfV0p3KzPgBjik=,tag:nUUrI1tpBRz+Esi75SerNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWnYwVkU2U0lBWEFvWlBB
            eElaNWJOaFErL2hUcjhUdldkWnR0YllHSndzCm55clg0Mk03SERuZFduQU16TEhn
            STB0MHpEUVBkTEVLZjNrSlJpaFZoaVUKLS0tIHI3eU1lem9maTFJUFZ2OFBIZmpa
            UmdKQjRTTFRKOTlJQVE3SUxyTHNmTFEK0N6Jl89ZmeRRysWbKEox0b8NJ+STcZIQ
            qxb9db43ApkicflPWWRwsFQam3t7oZ7d85zjxBiaFkWI7SZnCAuMMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T15:26:34Z"
    mac: ENC[AES256_GCM,data:qKN7yd4AyxNJtkoPjnjehmeNVN9+Z0BIphx9KJDy0iSTbEDnCslllR0Pa+OQRW2gNQgieR6E5EMSG1NgHGL/nN1CmfFdskCF1QE1LuTsqkm3nZF51BK1VOlGQK74743E8+8Fzqdaqg8GytszHu3BnX4TQdQVDQZcIHxxL3XP2FA=,iv:1uEG+LeqrZwkF8Hq7wg2jhsfBwcWjMlUFV9nqEkJxh4=,tag:wy8brTiHfeaUqgCpcDJa8w==,type:str]
    version: 3.13.1
