apiVersion: v1
kind: Secret
metadata:
    name: primer-s3
    namespace: apps
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bfiow7GkgXFAOn8ulIM64s59y+HyoXs=,iv:bOsYZWbqqSSiAoOLKy2Ggwl2FSCsHSxe/dpj9TqhM7Y=,tag:M62lVBGrZ8Wvew6NDDg/+Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BbqcY+1SG2AMDsJDa9jpyP4Af2N1lfbqua6HQXd0PtX4aX+h4wfvjljpkfg8Go/V,iv:Eestr6tE6agPax6n3t0eD8z8TjfQB1pvgAElbuh+EnE=,tag:5nlpWula4e74AHjmURxOlg==,type:str]
    #ENC[AES256_GCM,data:+8dIL4DlS9X0yE2GtrlmHFyQMmCpC/yGjTp0mrZRwPeBHKZGmujnxyrIRcaG12eYwSRMtNadSV1POscA9ACS6PUuIKVqvX6VzyI=,iv:+jfhoTWhDBD14VaAw6tpttbV9bcUiYIzatVAqaks39Y=,tag:GJY1XhywfsPZAAD6OnqRTw==,type:comment]
    FSSPEC_S3_ENDPOINT_URL: ENC[AES256_GCM,data:BfBSYeDVQpJr2gZkv5X45wXcON0UU4aL/e7ZnvQHBXLyJL9wBYJPvfTVSI28IQ0=,iv:rsfx28P88Kz6chjrKJc4eqgcYdUKFnLl4eoRRfyuzhc=,tag:usp24yMQnTwNiB4qeNm55w==,type:str]
    AWS_ENDPOINT_URL: ENC[AES256_GCM,data:+xRR9hz8ewvxVpYjvm9p7hAldw084C127Ay3fSHqKPAuCXx1gIpBnpqDmOELdNg=,iv:C4uA+6qNvnerCuYv3EUDuABt0dXlIUwvOuJhmJoJeuA=,tag:TMJWlDlrai49K4f4YUsD/g==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:wwvbXS1ZcfU1,iv:0jU/WE3evbhjjC3JhGUX+lQ/FYGfSdMNAtGADofJxA4=,tag:kTEVjnWvhYh3EwhKRYZQUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UmplbUpsemhJVjRrcWVE
            RTNXWUoxeUM5U1pmbGxvQXpTUzZabkh1SjFNClA2U3NoRzl2U2N5UUIzak5vZWty
            eUJ2Q1p0UkhIVzV1MlJmaEh6MGR1MUkKLS0tIG1rMjZyc0N0Ry9raU4zSFptK1Rl
            YUxmbjNNTCtNQmp4VFYxQVlmOE9VK1EKx2mnQPLIenAJNcQKGdaNdhoHxkizNSjH
            ziRVKLouZpnOHuQER3arWeoziGp/R/h1v+d5ObMCu6rht+LbleK/6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-02T02:30:15Z"
    mac: ENC[AES256_GCM,data:Ve8XkLq83pWFDi7IOU/KZ+P2HUzpcKnSDS1j8yEnIY9qYlbDTWwrjus5v35GOCmrGd1/38BHurKmF5X/8t7Flm/Xql4jq7kSqw+z6ctmgbl1GS/mcO1UClgJqksQJB3b/tJJqxAOa9Nk1tMEEozBp5GV4fzMlPBnA2moPivLNGQ=,iv:WTJxI3fNUyrbcWjEqUGtKFHI97WGnweqS/Otp7HulXs=,tag:7UmGUzlP/QYFHOPDjwF8Cg==,type:str]
    version: 3.13.3
