apiVersion: v1
kind: Secret
metadata:
    name: primer-rabbitmq
    namespace: apps
type: Opaque
data:
    username: ENC[AES256_GCM,data:Z1y9kQ2+ftQ=,iv:BnLgH9KJoohhshvs/87SYUzz8VXiWEvdr7AS5XhzKGc=,tag:Fi3Y8fJ1Ub2eJnjrEkmg8g==,type:str]
    password: ENC[AES256_GCM,data:16ctD6rslDHtGWj12lnepAP9WPFqCzuGcjehH1+QLACkOjHrxnjAdFRJOVznYDhh4vvEtz9VsUadO8Ax,iv:ejCmRCLgaILgGFTfE43Z9JVuLoUDF1mZEXH7RmqcTiY=,tag:scWjXVQkH9WOHO8Ql9/4FQ==,type:str]
    host: ENC[AES256_GCM,data:mxhxYb1AYwNQJcUODHCiqS+79rCngnXiIqAug/R3twJ9h/SBGavSLs3CbJ+rGX5euLCS+Q==,iv:v1jR8OJb18z2fa0sBye5DFkRIWAbrqb74ZPtq5O44H0=,tag:0DFFEwfiXVLfCFBYvhEZsA==,type:str]
    port: ENC[AES256_GCM,data:x7VWsPPChsg=,iv:iH3pwt+nEvJnPnppCG55ppUF08BBcTPwc+kJwhctPhE=,tag:snNmQvrTkuP+PhmEOotKcw==,type:str]
    provider: ENC[AES256_GCM,data:4OhS4zmDwPYjD+Bx,iv:aG7F3uRv4JJlaEsgpVkFyUGG4OEodBLvopeR5a4Ctkc=,tag:FgkAthNfejeGTGHuHnvTRA==,type:str]
    type: ENC[AES256_GCM,data:sFeCdRpDpuxMj+MU,iv:dMvIyDtChEVyjQKfFkv44Z+ysAZH1lpK/BSlQkxb/2o=,tag:P52CMS6NhOPD3ozAfccp6Q==,type:str]
    default_user.conf: ENC[AES256_GCM,data:X4LYuFfkqfbBJVJac7uTHjRRedCstfEoEo5Dd+o0ocvrwIGYntUvKcNVjk5++fno+X9yVgrupBvIdZ5eq+wOooaf7D0uzsYS+lE0tC4N5tsM11g+FKIZ0Riq8MrsmFmWxWwctS3vHSBHFgyV,iv:5+oLsT0WhBr7KTX6SeY2utj8Kpd/YlzX1cIidNWr5Y0=,tag:904K1rgXdgPuTyp+1SvVmQ==,type:str]
    broker-url: ENC[AES256_GCM,data:CM59rnylo1KywCRVPtYG1U8dDBDRyzUbZ/2LLlbKP1Dq9rZGfm8NHepHM8KLKocRnctOeto6ViG4od03E7wW1jGVqUvB0PKi4fGk78fOQqkDbtpPjTwJkpKRcWTCMqC+XPRqBTho+jGOJNO92dwKTG6bKcSYp8pkbGUnS/E+vTkzIMnHPTYhYciL95c=,iv:bxEjFr50bVYXrHsnky30rcETwf9qML8sJSAjfkQEzko=,tag:2CtFmRzfT92cji62HRqqow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicGNobkthcERHNWRxSmpC
            Q284VGwrWjY2V3RMaVcrQzVwbkU0NE11dEU4CmhtY2FLT3RHTTUxWUxtTkVPRy8z
            a2pESExtM01nZFYvbnV5RVVKbVNadW8KLS0tIGZDSXZDTnNSVVYyZUNCQzNlWUdm
            NDJQUkpiNnlZaGlzOGZ2aUJVaDZueWsKU2xnWYSSlIh+LmKJG7j/jgGE3Ly+n2Xd
            273flqdgNwlt6QZcEJisc8WplDc67zh5n1z61+bEUguvkyb+Btt7bA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T18:55:22Z"
    mac: ENC[AES256_GCM,data:tbfKHL9dKu0p2cBgHIfTJbu10ADGujSV3mc10gujGfEXi19dfZSnrN+dE3243oWlEZuif8Ngwxa/8QRsk5COb32vjge4S8eAyOq7QqCL0MtIr/T7klInCOsYQ1Wab7AtxZ4Fca05VvyiV4UpjC9AP0AhUBT1bOxtYQInazQBZpw=,iv:y25gLYxieUnQeK+IcZ76RntxhO7ZJy+Kov6Dk/10FNw=,tag:yUCDTfdaR7HGBfo+VtngAQ==,type:str]
    version: 3.13.3
