apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent
    namespace: apps
type: Opaque
stringData:
    NORDVPN_SERVICE_USERNAME: ENC[AES256_GCM,data:3fddbEKGTlV9lclcQZJbgwSgme3zsbJK,iv:u3D+NwQ7YfrjF8BUjoeViiHCSigTfkbhAy+BpkTegY4=,tag:ZRMNtSAWrIO4G3ck36MkkA==,type:str]
    NORDVPN_SERVICE_PASSWORD: ENC[AES256_GCM,data:DWdzwxIQdxEg6jj4O3OiJy4lQ/7L2XXf,iv:P1R/En/VyYJsKbBjHB2cynYoKsPN++9/4mwD4MxN5Lo=,tag:bxclZRqoCW90jLS15wn1eg==,type:str]
    QBITTORRENT_USERNAME: ENC[AES256_GCM,data:kLz3DiU=,iv:SLDCwyn8AMxIq/R5NM49B1MXCFZgoT4AEox6jwy86rE=,tag:+AaXDgIKAP/jBFLsR/3wmA==,type:str]
    QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:fTJYrBqr7iZsLUYyktEbCa548uEjfts2X2TYp5rwyFI5zcWcZo7YGzxbSMTD/ArR,iv:zfX0lR3cJ5uJstz6XNepx9my2qDAPPoig/+2q+JeIoQ=,tag:RQ6yMak+DHNTVZXyCsPxCw==,type:str]
    QBITTORRENT_PASSWORD_HASH: ENC[AES256_GCM,data:ZwY56vf9eWtdNuXpvxGbXOcbabCzYo4x4euwSUTdCbyx1bhDjF2BjW2dLzp0TlwYEzfQBnMjQi3qOO3soxlz+6cqwebm87vak+LUisFH4Dl/JgIVRjp3Nd5fCQldpR9+M4mBxPl5E8SIyn/PIMy5p+dKdtKeLwwWBifQhdiSSA==,iv:bZs+A06pYlv8pIpU533XoeD5LWDHLkFSw6s8r3y2tMA=,tag:IOJYdA+BjJJRqVdMtQ5cyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRlFpZytvQXY2aEJFSDBr
            U0JCWDhKY2c0ZFQ4Mnc5SDUvR3JhVVlYOGh3CldRSjBLWHBuV1piMnE3cXd4WElC
            dmt1QlQybFdlNTRLRHhURzM4QTh2ZXcKLS0tIHoxT2FrbzdDOFNkVTByaDgzM1Er
            OUhPZDVoSGFyeFVqakY3bGZqYkQzaFkKfZNDYBIIOihRuDF8zZFpJvv6/f7WAQ1Q
            rgjK+5aNsfAkqYwJQbPW52FifIcrx6xohyuzSazOX+0iS3zuJuBwtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T18:14:42Z"
    mac: ENC[AES256_GCM,data:+Jvpnbv6i3VKc0uzlwl0f2uUcABxLy/Xam7Q7KSbq4VQVEbB70t44wgSbdm5W1RvjhGsPqF93Sh9i5HA+D3kMzxhc9jbomUrzwwxcvhLUGQJ45w65VqixbJQJhHoW931g7cvXmOIMLECpeHuncGaQ7oVcIDZBth0F42vNbdNd/I=,iv:BJxMZ0mTq4XplhNcgXuKGoV0LSVGAsKd4KqKDtRhP3s=,tag:Mj4R1oCSa/0ElJfAnjrR0Q==,type:str]
    version: 3.13.3
