apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: apps,media
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: apps,media
type: Opaque
stringData:
    NORDVPN_SERVICE_USERNAME: ENC[AES256_GCM,data:F7xXw2mthzcwf1xFL+o/jfO1SvjuHn0s,iv:37aJIHXOjDbfWJ8Oa0yuqiPNjZtTLTMxfsVdpkfSUuU=,tag:N4Ir3g0Lbm7hYJF3nphlVA==,type:str]
    NORDVPN_SERVICE_PASSWORD: ENC[AES256_GCM,data:dU8pIkThr84GLv99vgdLbcSoe3UsuXXF,iv:9uxd5ltcyKx43KBqjJJNTauActLZNffvkA+ovkDWNgc=,tag:5uPXRUXzZ1OtJ9ihku4UUQ==,type:str]
    QBITTORRENT_USERNAME: ENC[AES256_GCM,data:BaHgtEE=,iv:FEGv54FKVLJvNUK63Jm/ztgUvThq8XkZr1ZrvP5uSck=,tag:LyTsP2qawuS0Ko+dsgMDrA==,type:str]
    QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:yc/qI3tSzkzTh+LYAudlNSkuQp4aecVDy03BbjeQ+maoCLV/Xb1cdIV7wMTnjkMh,iv:+INX3X7zdK5pqTJClwkRsKtJ2e36WIWDnuHPD9W0LZo=,tag:r6DN2Z114JslMfkCSCipoQ==,type:str]
    QBITTORRENT_PASSWORD_HASH: ENC[AES256_GCM,data:ouh48sp3wjKJN1MVN6DEaus5ynbJblHvBBVnaD1SE0/xtW+UT+SZjSSGJfq+bwA3IqhOu1eaiTcgcXJzgokjIo0qIS6/MLpz89eFaBSPhI8IUcbRCWERCfTnVZCqN0GpVi/6ULQXYtEHV/bLZeI10Mzqs2jlMqnA8qGeWAeGVA==,iv:/8h+TyyCb6IgxTTx1Pp2QtKbJg+0mNlL4HbeQ+AIe0Q=,tag:ULl3nThB+0kRAZKh2bqKig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZDlidG9qYzNmQW11aURl
            N1hPUlhqQ21DUGtzMmpiSi9TYXVFUE80RWowCkRpa3FFdTZYUHFIaVdEM01BYjNJ
            NlJYTk5vRS83aFErWlNIODF5LzNzdEkKLS0tIFpTUkF5d0RBZzAyQitpVXQ4akNT
            UnRLTXYrbUZReDQxWXlmTkhGaFJkc0kK2al4/xFCnXO/KAicNPTxcXnSuoeXAi4P
            imaLvZsiZTK+EBxAaAD/br729nDFUFOWI1NB4fxQIKN8nhcp9x8woQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T00:05:59Z"
    mac: ENC[AES256_GCM,data:PvbZVGwbfkDBtqRo6xEXa2YvEgHOTV4CYXY8jI3xTC8coTYfDXWCXZxJWEzTcuQYl5drDnl7QK1zUlI7Gl5v0QaKBaa/hO2KVcQps1rxexskBGL20+fDx28N4V/9rfqvl5rUL5xI2OGOG0udhpToEP1gkwrUVa2lPYgBQODr97k=,iv:TQ4RHTiSu21c1HdRqsKXx+0rgXkLbLbh9EpqTfvNHIw=,tag:Tsej2/QYQGzvgU4eXmL29A==,type:str]
    version: 3.13.3
