apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: apps,books,media
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: apps,books,media
type: Opaque
stringData:
    NORDVPN_SERVICE_USERNAME: ENC[AES256_GCM,data:PAvTBHVHYFczmZfQ8RMpt7n4P/ZmR+hr,iv:/GBQIzG2+o85+K/dmq7DoeCIT4cxJ1ex5ZrhLMyAqzA=,tag:wXmzw7sQza2R/E0uXrIfAA==,type:str]
    NORDVPN_SERVICE_PASSWORD: ENC[AES256_GCM,data:9PcKDhL5jvD7ncd6y8vn7Gdsxrz86CVq,iv:oGTzKPfUVeBiD4+OforgJ940/U4KOUSkEtl39/piNew=,tag:Yr2foETpk6+mvvbdp1jx6Q==,type:str]
    QBITTORRENT_USERNAME: ENC[AES256_GCM,data:+HNlAQk=,iv:JYfpCHNClElGvBgVy6vCiRCVRbsHZDJHNPU+js3hCbU=,tag:rtAGuTcmEGfHy4gH8AGjdA==,type:str]
    QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:qGzG+9rPbmbgpiHIu476+c0N/zVYbM9t2/NpRw18ojCgbEtZ6S9QQQ1NXCAs1fR5,iv:5/4T5n8dn1JFFL5ttFrX0okDekFxJEI3egCqDGv1pEU=,tag:JnLfHe3pYwthM4eqwJL5iA==,type:str]
    QBITTORRENT_PASSWORD_HASH: ENC[AES256_GCM,data:Z1vU6KZZyLimt2BJgY6cuscXMGc+CdVspHgiNrt/j3r1ceQYd0u2oSnAqfMNJXYnY1eA0C0by0uMRSZudBd5DW7PlVDDzm39DphBpYLXwY9vzXztUbUmpwVSyGaxQ7tgi/08sm27ejXAfJF/zg2KpEvPSF6/7G0Oj8zAeCcYdA==,iv:F2WYD3MzhUZcmBOtkoe/8RpNaZJd2BOVNWj8n1QsB84=,tag:efKd+t4wyM8jHcj75KrhKw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdjRialBBTnB6clVJdzdz
            S1l4bVNSWi9iTTNHZWIra25vTFJzTld2R0hJCnhCcjBWai9WNy93TnpPRWxKblRq
            VVlSN0tsM2FiYXNNeVJGRUNZVDFFbkEKLS0tIERRbjg4QmszVFc2TzNQWitKcVdk
            a2cwSGVlRTRYcm80YzV1d2hTVkpkd2cKKclXZGm3rgvRRrv9cQItB8j7zl49FqMi
            42QfqcHWjoiLLiqrbl5e1xXakxFTvqp4y5GX2h+dyZsr8UuRTgxpZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T23:23:10Z"
    mac: ENC[AES256_GCM,data:USMXSb4AXDdphpcjS+NEjfUNn5pQTqsrUmTY83VSWlv3doOOuFaLtB7g5v4kCabfqb/TMpnjEivCL96S156DfrSL3O1MAvMn5Ecq2bz6696v7G+N+u+vHsgQTR/Gd5pBP6jDTpF9V/QlYv1472fJ9Safjd1V2KufY/TxIrjTDiQ=,iv:7/GI/OIc0irgfBaOWxaI3IIpWnxjq4cUetW/tq1Ty2w=,tag:QYLdEA3HTwJq2maVhTU4bg==,type:str]
    version: 3.13.3
