apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-admin
    namespace: apps
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:MZQj8Ms=,iv:8IB/PcKCLskDrcP7XCV3O0CBumCrHK8QKA/JeBcZ7Kk=,tag:cLnO67W5vpXsIfMhkGS8aw==,type:str]
    password: ENC[AES256_GCM,data:sm1q2iSQdc7mozE7MIpim8RTAvGpDPnriDXmvmb0ExY=,iv:lwZTDquXgXi2RrfuA3oAwPHwuUwsZbCeDOuEP7L3Qms=,tag:DDHjgcopZIQsjUNJv9Zs0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbUlDVFJuV3ZUOUtXVHVa
            N2lUMjI2enB6bjBNK1BpcDBkbGdEa0orczFFClhFR01QMTlHQnh0UVJFLytGR0lL
            VUNKMS9IN1k0K1Z2WXlxT1VGY20rck0KLS0tIHBzYVVKMlVwRmZsS2FGUXhKeExZ
            VUNoZUhHcGlqTVpNamhESTJPQ21xWGMKAB5VbMnFBZEL94+LLdQlhgLPOtNO5RsO
            +W0s0UT6o2bwPZkB2b4fhVdck9LnZaPEP1KXUCNFEcw920ywAj2vLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T06:03:57Z"
    mac: ENC[AES256_GCM,data:es7coUuFg0rn+WjEI9v2FDMx8o47tuPMNUh8xzkPy0bLp1VHf9N3ifmP+smGZmYCwZi5CfjsE1ObrQYLtPPEMqBARj8OFSf7sJsgD3WttqIccNc0Vr0kOB1CAOPvzxGxvouMy9rlDZWwsluqz3Q3V7ZAj5UxAeCd0hF3w34ikzA=,iv:PWWnvo+00JXAuPSv4cGlIOMXsQqacB0FJNWsdYtcEq0=,tag:6izKtX83YPhvES6b7pBSCw==,type:str]
    version: 3.13.3
