apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: apps
type: Opaque
stringData:
    seaweedfs_s3_config: ENC[AES256_GCM,data:/saagrXsCgyBxCFsFeK/RHzB64GHC56HGneMyx6xjESmQJqjNJh1W6Q47p5aQqYfncIJT3vMWXZvH0VYNgEcmFpfAgEg9BnT4TFgsH6VGytQtz2Df2iCUHZ88ZJMFc8ymCkVPk6YSZPBmOiGajBXTYkvqOhmbf3LRebM+LcYrj/qoD5MLbLsSvsgBaWgAM9liG5sXP7A5OWIPU/iMI/snzVf1LFhkTjeI9rh63BmK8idc6x5ucKtJtgQ97sryFvkKuKernRwjGwTsgEwOB0KnkYYO5ilu+ooVoj6RMDArJyhDTCgiyIqwLHIG0cfdTEmzzPUWKaCtRfKJBYpJQsXA4j7cHnp7zPmfaRwBZNWyN7fcPxJKVHStzJMfBQ4yk/5eN2ZdW4jSy7a6EQO+P5WAvfeVeutkn14JlJPsnF0mfLhWRtXVK2It4orfrfJAwJtkvwRxoaL+4CuDzF9RVH05yMl9pA0ohj5PQP0sk74dd96uLV8KCB749PcBeYrmYb1D6InZbYRgIaugvOD7RWQHv6ddCgRUB1shotHA/DWgrZ4Mp86t3s5xb3iKFqnJh481Cm4OrC2EEAAzAlUF/jvC1jBr3cQ4Qo5gZ637LCN72QKByk8xJJjiFNi61xeJFG4xbYGiu3HR5pvfq1jDq5nQHjZR6D4Mg5hkziYAUqzGlwwH2u7mnnEVh0zFQ+HVTJMvSwwiGw+/sDROy5fspPrCe5bSYP5MPfy2xX0cQzIrW4GxF7ArbfPbpgspew8/2NR+IuvEVoORa3bEw9I7UjxPchg4hocHeVG0P5j/alOIxI8fH2sQcd+YOaFZyZDiKF6UHrda8HP00ItcXeGmTP7fGYI9Cfqso9B+WB2xHJI4RQbtIyVxG4+QkcYeiZ4jq5Ji6i0o/AnD+J+0aSVj3h+9C6xmvWJtGVfj/XA8yiVTWv9zjS9wtRLtCZuk6t73G+RJp/7Y8WUs+v0CkNAw+KiMqpARcmWCeyaGAy5g/hY9DYQXMlr+tstLpzrxS1wvMm63BV0hefcLZgvZ2qmGFZY1UTMimDCNB1nKMqv5wP2eTLzDN4YCYsymtE8PHfBvFclVdvoezevW8Tjk9GskhdHevQij9FcRKZDXI1bSPLjOY8CgG+MnCDOucZn42op/kqWnmrK08r7X3bSya4f3qbCEjCkfgnU5sy0Z3CkciKWgYb+KYYEwzCwlrlcyaY6ShwPUAUJiEuir+C7Svx1CBszXumsr2aenUJjLHstzvyKC0r0S8nwQPcp7Wj9d905MJteXeMpg60wctIe4LSZVhoFXofO9J+Mc/IS9dlQsjnY42iW6kklvJDAtyx9hNAva0NjUx/wOJS90Y4nnk6ZXmjDHSckNS2y4HKAYhnlJAbF5SCO/kRBZ9fRlbdWD8KyLfEmMwQazAy6x9lKus3RkY9p3aWVQO40iEzM6t0YZK9JPFUb5eNR3MXD0y8=,iv:H1SMfr8a/+GmGNqRbmoePkb77zXJAgbHkU7nEyVKGH0=,tag:OeDKz1GEsr1A4uXOcM1CNQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNjFDQURFSEY5V1kvd0U3
            eUFKTjB1WFBSQTRIL1RMb05EY0I2WmdSUlJFCjdwbFpYdWVSTFdYNEV5djVWUUZP
            ME5VZlN1WjlyWEdEeTc2bWJHUmUzRk0KLS0tIENLRzA5dzlTL3NBM0U5U044WmNx
            bTZDN3BIQ0NLZlhsWmxwU0gwREE2VjQKSaQv9Uyuk6Tp9a3ykwjiTYa2gSDefUpW
            KvBQaCwuTvJH5H5OPTMAzny1faqcfckduUwkytDCfSJIuuw5R/rMQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T14:28:25Z"
    mac: ENC[AES256_GCM,data:Vwawb0pN/aI4mywIPXpfGyrd8k8goGqxs0i7PldHxdsaV8pP9WG8KLhqdqK56MDoFUnjBD805PC21wI9mcZDcrMzNxGrN3pCUthbrGTJAGNZOW75hxAYCJJaBf/5CV+uWdY0r+EEG28cdEURVQaQhIlPvPbM4zd/LR03E3XvYoI=,iv:xxecPWtMRKS3xrop2jEM2hy0XCSv8TzXh+RdMll/+E8=,tag:NeZRMjCCQlD5TUJFn9hoCQ==,type:str]
    version: 3.13.3
