apiVersion: v1
kind: Secret
metadata:
    name: swing-thoughts-auth
    namespace: flux-system
type: Opaque
data:
    identity: ENC[AES256_GCM,data:JKHIliiD3iLeYX+k8UMkRu+qJdiqQ9C9pTR6puxHYiepPP7PflPOfjXWsLR0VL6lZ88nem3oL8XjduupCUk21PuQEl+XJ0Pe+KKKcelEr5mnuxqKP9L0pEIHiIwgJ4sXqNsA+DhHZp7s6Q3KBaRnt3mJKx2c+RNLGEIs8H9XD72zEWAsFMNXq1ihRLpXNjDjygZP5YM4AuRjQTj7Ep0170aiOQN81U1v3nRW961ZV1IyubjNVU1anRO7GK9NzXcuHXD39kjUblDwx2K+ai2qArILJqV+7dN6JosqthYgVewls0uWJab5mSYVyvQIORos8038nAouvpvuWGpZAsiMEi9YVDoY6CBiaf/1uqe35SKxj0MqjGFVfnqKpB2g5BZJNS7I/UdFySgazFUfyErKG7lEsSKH2NSbjUgpb0x7N1Y19VZ9q3M9zk+3hT8YMpWYdlteCMP3N7h2z/cwXRUeUbke2wvGQqb7AzmCLWbfKr5eiP0wKkiWZYcVvkRnEC0j+Wg2X1K30o/rECAFC5pEjI1VxDWxucdP,iv:pcl78UdubllyeGpEFU80SquyfLRHjc/4EnlVLJ0HLDo=,tag:TR3uTvGDu3l+dhrPvl4m5A==,type:str]
    identity.pub: ENC[AES256_GCM,data:KO6rFgcqLmgVuI1eW0MkN9imGrpb33zw8QVNbSOXviwpJoIFTx3h0BgbWnETqkfvtRPVil8Zvn2xN3f4rjgacYFq00DVAauJh7IY1FNmW0kioYt08f3udmX1BX+W7m6OJ522FWSkdtv/KYoDY/OKfBbW8v1Pbi7g0slfcBPBeVv9KsmX2GRQ42ZtxuQI3yYnpzpLI01a/PQzbM5GWc3IWX5I127UpFEnU15M02kzqt/HVXC2Ecypn9iICZ7VULWhvvZT1saYdVmxjsMIOUYRFnnIHhYPm6C5ZVmOnuLI1cmT+uWqKNIIaZog3Fe0Rt2J1Lpphl1SFwydvK1THH4pSI8Xs6vH1I+E69nHwZMHqUsansur,iv:OwTafrnGJPR883mzGOTYLCtEfpBUUG3op8vM7zEKpxA=,tag:b4wlJXrHsGxCheBYt8yZ9g==,type:str]
    known_hosts: ENC[AES256_GCM,data:/akOXO9nirTEFFmFwdehfmbkAjGVCnTqZ+RrVsqVcxPcoe+AgUoJ68Ke5DVXXKsXY4MtmkjY8xU8hQGFpsqCvPtkybA+JASsO7WbMnbdH61+BcXXehXBvXs8ekf3HnmHijHPqMF8DyXg5Kqc+/aR9hQc7Wgm4qvSZzAgcBhv7VbeRLwQhPArFdypI2NF7tLaEQ8AwFgzpTeOFutSEJ6krh7kLCuj/AQyhZRLlkcFLHhn1Ar2+ZjsZD+WRsyxn/J4GXBzj43VDQfzsquimqmCkxjBbJFHB3F7qn4B4O1OcQDRJhAd,iv:Aclw9ZzXXb0gIlXaOQ0VHbMcTrua+1gXGScD86dHcHo=,tag:kugtUzohRHW4VXqlAXfsQQ==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaTdMb2l4bU51eTRCaHJT
            Sm4xU295ZzVpSU5nVXpDZDZZTHdXY29ZaXdVCmJkY3pPSlZVSEtBR1IxZlZSWGU0
            NmhzbVBVOXU3RkVkdkpDeE14N0pGbFUKLS0tIGxTRHZUZDVGQ2dHVVpObVhHaVhx
            bnA2a044NWprYStPdVJNZnVzRWNLWEkKUbvC2B/oisghyWZrmsguwA6P/z9NGFIN
            cuv7vlc6C+nj7UwNS158Md1WHH+sm+notMLBvl6QcykkkilTWO3r/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T21:20:32Z"
    mac: ENC[AES256_GCM,data:ZV/yXfHanHXpoxmrzxB9kzL6YiaOIL+/t2JkEV9uZOb0nV9e/vfKxmxoYTdDWNfrycHM9LP2pc8aT6Kg2ZcXcSAZmihKhqPnBS8g3/jyuVajjgKw/seIcqvqZ0DoGiFg+HeGeB+pHIpYod3+orzkigFad9E4a/5+yFaylSNo900=,iv:AdN+T12V1dt21BDacTWcmrGkExo1ryV3kv6ePSuv8T4=,tag:Guy4HvBYINoyNhnzF4i5Pw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
