apiVersion: v1
kind: Secret
metadata:
    name: vllm-api-key
    namespace: apps
type: Opaque
stringData:
    VLLM_API_KEY: ENC[AES256_GCM,data:R7tBnnHVxE2lG8BnG4dx15YLrTE/QGWWfEItezlWllNhyaThr70f3tQBaRcE+Md21H83,iv:m/4JuicJ63fwUh/Q5yw6zgW212rCRfjA3eJKVmmE31Q=,tag:ypz1B5YliSoovOpNhn6OKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNGlGOERTQzl0SWhEMkw4
            RlYweWE2N3QxUU9EOERtampvRkJHNGdMR2dzClFqblpKMk1POTRvSHhkVU1pZnRC
            VzVtWVkwb1pybTRiNG5oOFJEM1NqaWMKLS0tIHhRcytDb2ZmeUtkem9OdXlwRWNa
            cEc3ZEVtT2dxblc2MXhqTm9nU2hYMGsKrB8sFHoLKAvYm0+8s/2ryco8X9JjQZAp
            fdV7Vkn+xbQeL4itlRLWDuB3avf5hcjmS+OSXPeC6Zj9X75sJFzb4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T21:36:15Z"
    mac: ENC[AES256_GCM,data:GAVLiM3GCIOopGT8MnQNFywDKpcRcyiqmVfnA/lCZFEdJDrLCLtWro3A81ClRPvEvgJCdQn9Ms4xUHLfv5kUmldRdOwwsYZckBJ6zl3pjI36ucVZTNRW74deHxCq5foVXaRna1Kts3QxwWwJAGmj9kK304kxtOKVShZeWYx9oTE=,iv:rmXcsez3shvdyxtjTaWlEdVhoXAApiYVfhgs/4uWk0Q=,tag:Z3LqIPMNKiWt4rNFdVcYeQ==,type:str]
    version: 3.13.1
