---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - deployment.yaml
  - pvcs.yaml
  - services.yaml
  - ingress.yaml
  - cleanup-cronjob.yaml
configMapGenerator:
  - name: qbittorrent-scripts
    files:
      - bootstrap.py=scripts/bootstrap.py
      - cleanup.py=scripts/cleanup.py
