---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harville-wildcard
  namespace: apps
spec:
  secretName: harville-wildcard-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitoring"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns
  dnsNames:
    - "*.harville.dev"
    - "*.int.harville.dev"
