---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 1
      remediateLastFailure: true
      strategy: rollback
  chart:
    spec:
      chart: longhorn
      version: ">=1.12.0 <1.13.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    defaultSettings:
      createDefaultDiskLabeledNodes: true
      defaultDataPath: /var/mnt/longhorn
      storageReservedPercentageForDefaultDisk: 30
      defaultReplicaCount: 3
      allowVolumeCreationWithDegradedAvailability: false
      replicaAutoBalance: least-effort
      replicaSoftAntiAffinity: false
    persistence:
      defaultClassReplicaCount: 3
    metrics:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
