---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - helmrelease.yaml
  - local-path-storageclass.yaml
  - longhorn-retain.storageclass.yaml
  - recurring-jobs.yaml
  - ingress.yaml
