---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: swing-thoughts
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: main
  secretRef:
    name: swing-thoughts-auth
  url: ssh://git@github.com/isaiah-harville/SwingThoughts.git
