---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - omni-backup-s3-creds.sops.yaml
  - seaweedfs-admin.sops.yaml
  - seaweedfs-s3-config.sops.yaml
  - helmrelease.yaml
  - ingress.yaml
  - backup-prune-cronjob.yaml
