---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: apps
spec:
  interval: 30m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 1
      remediateLastFailure: true
      strategy: rollback
  chart:
    spec:
      chart: headlamp
      version: ">=0.44.0 <0.45.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  values:
    config:
      watchPlugins: true
      oidc:
        secret:
          create: false
        clientID: headlamp
        issuerURL: https://auth.harville.dev
        scopes: openid,profile,email,groups
        callbackURL: https://headlamp.int.harville.dev/oidc-callback
        usePKCE: true
    clusterRoleBinding:
      create: false
    pluginsManager:
      enabled: true
      version: 0.1.1
      configContent: |
        plugins:
          - name: flux
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
            version: 0.6.0
