apiVersion: v1
data:
    identity: ENC[AES256_GCM,data:JO3Ek9u71RpV35PjaV/ZW8uuew95QmTrtEFBVvlSaLeV9ERzzH3Eog/FNcRFPWtAHciQMW/VyXzV8cxGFZBB8hLysgHk09dI4fypzVznqRT/Owmsgb22R3HgF5pKg0TfBe9VuMI6GyRmkPHZHfeqbTdOMzAwaLhf7TTHg30t73K0SC9sjKkp4UvgJKc5v/kc3btV4vO6Erb785ooBc8XMc3dZF1INua1ni3M1o0Cr5Wx/m125T/hQfgjA0Co4Hzgh/x/YANLs4bhYImSnc+wfdEfxD43Pd3TEuMpBGF8On1PWMmB8153TN0YTFfCM4HLiOUXawgqYpppO9pqmCQoK8dU47wpzfRBLAsWOTweqdz1GazWf4bynYU6VqLG/ktU7K/rfxd8a9dm16NHgBaihcrc+jtTKiR43SjsD7/zLOuo0Aos1PHs1NOTPOTbhnCBiw/Hk6IJ0Jlck1+nYKSXWm0xxoGxWlCkhbPjk1OWell2iCk87iPjzfUX0ol2BgMDbIt/AJYJkOfd3gSe+3xjwZZXpa9OlyCcsNSLuw99lxypsfpL37o7gZJqbJ1P8xjFY7N8mVM9oBT7RErOsq0vJmCXsGLz3RGTfW+OyvlqwiOMMnNyyIAx1BKBdzKJ3liuajlOjOF4Ip3eu7O3NX0hxObJnbmSCjdLCCRvqzMd3yvWRlb0wK9pYHQaEFWIRE8heK0TAL5KDUsFyQkQgDKnqm4n1x0=,iv:poG/XHEGZK0aDZ2TPRfnzb9HKEGEMmqJRi6ElsU/YVg=,tag:DAYcf6OTFJI7gTu0aW+aEQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:pm6SW04WISvlwA3os/uY8+Snvqa4s9Zyy9raOzAzU1kqOW4lnneFA7WXy0fWxJfZIquO8Ik62TsGbcXXtO4ouWBHcJhEbVHq1wEdg94++dxlrFH8ZRnHWbxa5MRuLxYKUfXZ6f2S02a9UUN03A9mMjvW58wyMXcson3yWwyYdnVWwRnEdf5apa1LQt4=,iv:dVKwgbVZ2SghJxz/MiIed01cMDzQXAVcCZNGXmsYDA8=,tag:g9xS8U71um+LncNXtkFXWw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Icz1qYVjzPZyHI6b6FmEyZ4qg7uXOq7Ex+ic30IIAxxxK/2RDUSIVZmTi4LVr2DBOIpCkUfurqRqtn2HHkd9KuAgqEKI6HXSBt+d1hbfpULpQKgB5oTP7o81uf6Q/KYk0Gl3klId5d/DUo5jIeslYYVGBF/kEFCeNLqKgucYoxA1Q6KLoMWL1rZmMRsiwlqE5ATIu0W1ScpBBuoEZzdJr2pRG8WQX0iJV9whYJo6f15OJnv1bED1azAnNc/OpBBnRCvv6y+MN6XS11l92cwr8xLAt+XW1r6F5jjNdR7DmirLmflY,iv:hKm90DzKGHe0MT5vSft7PKRqr/VcsstCh3bX2WRJCdo=,tag:VdtqT20hvJ0IadSV7jYK8w==,type:str]
kind: Secret
metadata:
    name: flux-image-automation-git
    namespace: flux-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZ3k2bVpMYWZSOTB3RXg5
            ck1zdzljQ25KZWtPZmhEZWZvRjN1RmNUYUFVCllwRFdkcVNWYm52cXBWVzRQOTk1
            cy9kUTJEeG8vMS9rKzZ2SFpOVUx0TDgKLS0tIE5kWGE1d3o4TUZ4Ym9NWWx6VFVs
            b3NqdkFRaVkzSElrbDBWaEY3YVZseTQKSymMliqXLD5e+n4g9R1YysiuOVxEAVtN
            wDPc/2ss1/GGYfh/J667jEZXvfuSWeBbi0OvbFWXDd6DqZvL9LQZ2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T23:23:06Z"
    mac: ENC[AES256_GCM,data:im88DCiGps4ZGQFuTlQC9QWWfmImQABiRoyY+cHO016qnps10kol6gATifA6pfpoDCE8Z7TDhPT/tjQTN5kM5WA3TcnLmiKy/ePhixaEhhrQCeUJtB9nOxBMM6tZii5BdUeMVu00GvxhaBgE3E/WOWbXna1F89FRZ7PdYIeDHUg=,iv:1XLVA0t4pVZaHzKrJKmxP4S74YDwS7fxe4y+sYas+tk=,tag:x/QvTmj5PwOtSV8fZ3UOOA==,type:str]
    version: 3.13.3
