---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pigeon
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
  url: https://github.com/isaiah-harville/pigeon.git
