# Encrypt after replacing the values:
#   sops --encrypt --in-place clusters/homelab/infra/secrets/actions-runner-controller/omni-terraform.yaml
# Create a dedicated Omni service account:
#   omnictl serviceaccount create --role Admin terraform
apiVersion: v1
kind: Secret
metadata:
    name: omni-terraform
    namespace: arc-runners
type: Opaque
stringData:
    OMNI_ENDPOINT: ENC[AES256_GCM,data:CVnIJAw/Bs3TiLCCJMB0lxWKHzPHzLU+FnE/Wwpe,iv:6Uj8tw55D1VqDHBv8Jy9EL+UJvfnf6H0ZJn8Sjwq+GM=,tag:Nb98+41H9/q2E1YvXmr65w==,type:str]
    OMNI_SERVICE_ACCOUNT_KEY: ENC[AES256_GCM,data:pJHLlEYbah2JxJefTjTFLFThWQbq1zbc0XTOP4a56gRUNrHD9DD9EBON+tAMpOFQtk/AmSp9dAPN/QmoFT0JyGKBWgh6gW34sQJVT1+mHp15MBhI9gheURhT3MfvHWp7Qv0/Bx7pV4g0BL1vO0HWZouoCH+yMnMoVx0hs7QY8ZupvVrxKesTyLIEGL1d2iBPmjvGZAvuzg9o6lQG9e+93mFArZt6SngzVzCbALiu0IiDeh4CX30BLvTYFGozlIATT8CqXbh+gPxja0Lhh1ryKmi+gi4bO38KIfYS5SoTVgPkdyYKsYAqYxp8TATcrq3SSBQKRrGcCwO1eiUGLmpLXqLDCzH4QySVMKpIXV7zZtW8Gja+WOt2IPG8EJle6h5qpAVhljw7g7z+v6f/h5G1VbTmg8ZogW94dQ3JApRnrEd5giSv8pLPDCrsvI+5wqZZhuly4Fx8FjurBhZNGAwxUBKXdHx9UvuEeJUJ92zYDLQqql9xe21KUe1HiwGpkcWvFfXZxrOXJrk1LILhvGyr9jqXvdSUTE/+YmczfkIEze4eVJTHEg37ZRXT+cigEH3EwqT76HU0n4irG5fBytk50u6kcXsXy0u+PW6ATl/xjoGLT5PlmfnXOiV78gpoa6KdcVDVGxgDGw8Ge10Kqbu4ss2ZDjJ90f+a6KppvphdJEzg7nKrfjE+hnC8ZZIFgTgG7oSPDKFqXmaA4VV5bB5rUKkrtET32QxX+ZTky6aKMnJ0DofZ/1fP45/HBJuSXwkag2ImYnb4p46HNVfgQFf/NQgylLEZDl44TClhcLQtCOvCs7InlzcgjEOOsRW8UGhgl2DTyVZVb4C9ZsVJYWCB6kvKbIbXF8EA8khqnFMLMmgdGWl2TB8nhKfnPpS2MDFvQghFAXaWo/s9O5Gb6zBvyvQNwLCYlOQEHUn1aoMcfV8NSN3Qrw/5fM4TQNJalJp7x5za2VlTeS70XfcPSlVzmuqC/dOl95NkhyvqFRJMqOr3gajrkJM87CGA+J/zIWXsLBZXOQ2BQjxxDO9JVQUqSQxlEjckgh9L4wWTAhGFMeTh3Pr7nmjJS6MaakRtIbMB8w0VjSI6qvtmKop7gyO/lryskzEik1CW2ptEOoCbqpfwT0b6YnlF9uBFIxqTH0opAGNzFdUJHvdWi4CZ6KJFcAuYDj1xN5/eHfPRAykS8HUWAOrKK7BZqX1ZsvlqumPYA486jYWke3GKyccvlKkTCDKisl60SyHnB8yVw3LeWAS/747PzphyAFuomuzjgATRlcZ42cGfrxlMBBfL46rbtXMek9e/YoH/uWekRY0CUjHuJOvQVe8AkQmkEdDIOQTpZHblpxv4ZP6bV+mHnG2Y3hLQ3dHnPbA3JjHmb3B0ePcyDOIHtOs/TyF0z9Jpa0FH2hKGwQzAfXVkjj5XuP2T/f0r/VFzx0f572lB7GkaZwj5j1IDgspRHUyPDb8UGebhLK5oz/M/iG+eZ0tCqYhxwolvM0ZA4F52qbRMIhgv+Nj/Rc+4XADudLXA2xHhaBdC8j5wN2LzAHr3/JlGtxUcHG75h++7bfUMuxW/uaYz+E7uVoETIcIrWlewjmWxxnrxfZwj4JZI97G0/j+FI/EP0MUBu8xw4KmeNDWBvioqDZD/sUpCZ5vu6mPkNlATvhf1Cl3BQD6zSTYSI6NuxNzFr6StvE7YSc+6ftdtKgrqfPbBN9vp/dvXTwSn/GsHLo34xObHtUD4nJSV62H11ZN7QSaw2vkOHBjkHD+R2t70Jg+eyxnkBNHrEsadqMf+wba+QEP5ZA==,iv:G5+iw1Fv6utAONBeE4hkiz1mVsAUDO94wAnzF6RGNCM=,tag:WJhEGqHKnmuIUBm0DZcHjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZWdoSC9US2ZnSmkxY0Zq
            NTRzZVliMEVwZ2NXNGpZcndzV0Q3VW9rUVhvCnNyR1pLVnd3Q3Jqa2F1aTlpVFlz
            U2piU3JsSWF2V2hKeGR0UnF3N2s2Nm8KLS0tIFZkblRRU2ZSaVJsMERodnhuK1lH
            NUFZMUFFK3B5TjBvVW9MTzIwMzIrWUkKMZqTSyEF31OPs3V6/+fYsFKJSWcKXrZ/
            FsVLsihGBJsOg/1SrATeqSPfY1cim8R0apguZwSWEZ1LSbWjCzkyCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T14:18:20Z"
    mac: ENC[AES256_GCM,data:NhfNrfmKaf0boX9EGpjuZLg7gIv98unoTmSIIOZk8leI//nJMAYvJ4NMu1g8ZcNhK6BlGNxlbKY1bwj52PMNoA5T0P4Krf+g86NTwHMRhDBoxXKD6YNdKDBxnZEORmXjY7sSyToRi1iZU2Y/04OHBik2Rh5gEAAD8pUddSyYjIs=,iv:UaL5avwY/6F1IcsKJ+byMwv+9QTf2uquLzr/Gj3ahZE=,tag:362HnA+wL4DUP35M+pzSVw==,type:str]
    version: 3.13.3
