# Encrypt after replacing the values:
#   sops --encrypt --in-place clusters/homelab/infra/secrets/actions-runner-controller/tfstate-s3.yaml
# Use a SeaweedFS identity with read/write access to the tfstate bucket.
apiVersion: v1
kind: Secret
metadata:
    name: tfstate-s3
    namespace: arc-runners
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3nEG45Pt9Ctkl1t9to5bvEAhpqA=,iv:CwlMH1GuEO/ARqNTR206Cki7LuQYnoxCzDOXM6RUpBQ=,tag:uCcUdUIGc0a0q2eKq1Fo7A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Yym9fon/nMehjj5GhtMe36M8GaqsfUQ/5KDxSPRBTkyjcjQawy53YQ==,iv:259s5ungauAAhVZzrYM+4O+Ewhlqf8cigaEuL23bDw0=,tag:Z7oczdUnc19VHG7/2nMvtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4d0Q4Z0d4NDRhQm1JTjJE
            R0pCaTFyNk5zc2M2VURlY3ZoVTQ2d1J1aEFRCngrbFZUbVJTVFhHWitncDBoMytJ
            YVh1cDllUWZmQ09aYmlWS2lqanlvUGcKLS0tIDI5cUIwWXQ4MVI0Ym9hZUNWaXlv
            RFFCeHpnZnhPbFlTVFZDdW5RZHlxYXMK9K6uGFqjZAdi4Iscy5C0uuUlocRAs042
            Zvviu+fyRsOJRmW78DMJ0/A+ZFNP6nV3Cu54Jb0TmRkV+VH7YeS12w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-25T14:18:49Z"
    mac: ENC[AES256_GCM,data:m+y1X+V7LnfADM4ZoUmyD2qy/No5xA4Lvc0TINjWdRSmRuUV+urc3+DhFcyG1XuhRSZRo5/AEESdDAsUVjremzp4HbLzirixLwknFZsY93wvXCcHONwuVVIoOz65XcvcbCHNRIuFQnKStriqjKfaJ925Ek9GpsuZFxMQnZ4dcOg=,iv:AckOS1w5wM06TZCsftYrtcjtsEcciyVzmeGaKgguFzM=,tag:gZ/MhxW84OVBJENYvzG0jA==,type:str]
    version: 3.13.3
