---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - helmrelease.yaml
  - postgres.yaml
  - postgres-alerts.yaml
  - ingress.yaml
  - middleware.yaml
  - callback-ingresses.yaml
  - blueprint.yaml
configMapGenerator:
  - name: authentik-branding-assets
    files:
      - harville-labs-logo.png=assets/harville-labs-logo.png
      - harville-labs-favicon.png=assets/harville-labs-favicon.png
      - homelab-login-background.jpg=assets/homelab-login-background.jpg
  - name: authentik-customization
    files:
      - homelab-customization.yaml=customization-blueprint.yaml.tpl
    options:
      disableNameSuffixHash: true
generatorOptions:
  disableNameSuffixHash: false
configurations:
  - kustomizeconfig.yaml
