---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: website
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: main
  secretRef:
    name: website-auth
  url: ssh://git@github.com/Harville-Labs/website.git
