---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: scriptura
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  path: ./apps/scriptura/scriptura/app
  prune: true
  wait: true
  targetNamespace: scriptura
  sourceRef:
    kind: GitRepository
    name: flux-system
