apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: example-svc
  namespace: flux-system
spec:
  image: ghcr.io/your-org/example-svc # TODO
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: example-svc
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: example-svc
  policy:
    semver:
      range: 1.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: apps-auto
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: Flux Bot
        email: flux-bot@users.noreply.github.com
      signingKey:
        secretRef:
          name: "" # optional
    push:
      branch: main
  update:
    strategy: Setters
    path: ./apps
