---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-postgresql-longhorn
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
