---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
configMapGenerator:
  - name: lucerna-site
    files:
      - site/index.html
      - styles.css=site/styles.css
      - privacy-policy.html=site/privacy-policy/index.html
      - support.html=site/support/index.html
      - apple-app-site-association=site/.well-known/apple-app-site-association
      - nginx.conf
generatorOptions:
  disableNameSuffixHash: true
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
