apiVersion: v1
kind: Secret
metadata:
    name: authentik-social
    namespace: apps
type: Opaque
stringData:
    AUTHENTIK_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:/xY5iMC+9PG28th+m0/Me5s1GKE=,iv:Ro5RXgqH73dFrLdOEmTVbhpaU54AU66+FIzFjf+emuE=,tag:iEEwlzhKkxADbvB0ZCww5A==,type:str]
    AUTHENTIK_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:jOSm2S3HnE9qVj6pdVcPvCCv189eyVtysihon83vegRyXIMOsqx96w==,iv:u3IOGWTTF8Y+eT6N3SeeKWru8RbCBxwDaBo+X1ZgpwA=,tag:ZAn5zJ8Sb5JxsgydPCi0zA==,type:str]
    AUTHENTIK_GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:k8j2XdgRWQpV7ZwepU24douEaJLHJ0xdKdvMSjXOtuiC1kjDorDXmnYEBJLvkMZy5YWR6k11AOfUfgP/B6kSOp1pRIzqK2Ir,iv:/IqFZlTaGpOhV/220UnCRADuv3jVVv6PlSkqrIggRMk=,tag:04chQjHmvVm5lSQyRWmlmw==,type:str]
    AUTHENTIK_GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:eX4Nn9v/sBVvWHUJl1mPQ5IW2Oulpeb45uA0+hWf4LCjkjY=,iv:OxIluBsbgcXChfVDCNaqFT+3Sda9uxT97fsCD7caSxE=,tag:4/8GuF0ety9y8GgeKHtnGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSnVqTUs0anBCZ0JuSUVz
            SmlvOVQ2QTB4b3VCLzg2dFk2d0cwdzVydVZzCmtoSFRDTUtDcWtEMGgwOVg1MVRx
            N1B6S3doRC8yZkxwL0hFcmhRMXU0NlUKLS0tIHVadjZ4UmhPU1J6aURkWVhWcldK
            WmdwNlVYUVZ4cGlNak00c09vSFBwazAKIl2yJVv61XuHQgJgNMf+3xb24EAuAcyn
            KuSCEPKUssCsXENPS+K23XSRkaAq9Nky/ftoPNeN3KOSewFMFPTIpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T23:25:41Z"
    mac: ENC[AES256_GCM,data:0fIY8lO1PSGJGnrCdecAP9qo6Bx0IW7q1MmvDmcrIiQFEJO7sHELOdvqyOG/DhYl+xQHnb9oWh/uGQGNAwtMWy1ezaAp87TTZCRnWL3AN629bVNVFfxCkk1s3oIfF5PpezYLmbri+pMEM+yIDEUjmSTcpMYUvV92Ub30mEPFWUA=,iv:wxW6617yvvM9oZMVRH6gzhRkEfimZVdjIAI2D2VxIZU=,tag:4TudH2BQ0QX3SqnQj3U6bw==,type:str]
    version: 3.13.3
