nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - kind: HelmRelease
        path: spec/values/server/volumes/configMap/name
      - kind: HelmRelease
        path: spec/values/blueprints/configMaps
