---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: orion
  namespace: apps
spec:
  interval: 30m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 1
      remediateLastFailure: true
      strategy: rollback
  chart:
    spec:
      chart: orion
      version: ">=0.2.0 <=5.0.0"
      sourceRef:
        kind: HelmRepository
        name: orion
        namespace: flux-system
      interval: 10m
  values:
    ingress:
      enabled: false
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      size: 15Gi
    api:
      replicaCount: 2
    gui:
      env:
        VITE_API_URL: https://orion.harville.dev/api
