---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - primer-s3.sops.yaml
  - primer-rabbitmq.sops.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - embeddings.yaml
  - reranker.yaml
  - middleware.yaml
  - helmrelease.yaml
  - public.ingress.yaml
