apiVersion: v1
kind: Secret
metadata:
    name: primer-s3
    namespace: apps
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:bfiow7GkgXFAOn8ulIM64s59y+HyoXs=,iv:bOsYZWbqqSSiAoOLKy2Ggwl2FSCsHSxe/dpj9TqhM7Y=,tag:M62lVBGrZ8Wvew6NDDg/+Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BbqcY+1SG2AMDsJDa9jpyP4Af2N1lfbqua6HQXd0PtX4aX+h4wfvjljpkfg8Go/V,iv:Eestr6tE6agPax6n3t0eD8z8TjfQB1pvgAElbuh+EnE=,tag:5nlpWula4e74AHjmURxOlg==,type:str]
    #ENC[AES256_GCM,data:+8dIL4DlS9X0yE2GtrlmHFyQMmCpC/yGjTp0mrZRwPeBHKZGmujnxyrIRcaG12eYwSRMtNadSV1POscA9ACS6PUuIKVqvX6VzyI=,iv:+jfhoTWhDBD14VaAw6tpttbV9bcUiYIzatVAqaks39Y=,tag:GJY1XhywfsPZAAD6OnqRTw==,type:comment]
    FSSPEC_S3_ENDPOINT_URL: ENC[AES256_GCM,data:/lBUNOO8uY4xqAvOa/2OWDBIPxGrsrmyzzzHH5sLYSj88B7Tgp5lyFWNqyzu1ynoOBNiLQ==,iv:LubQ8KgdaGL3q/LuoDOgN11isjGDn6wAARXl0RwTCxU=,tag:epxfr+Dw+M9lO/x63m0n0Q==,type:str]
    AWS_ENDPOINT_URL: ENC[AES256_GCM,data:XPaH6sWn/vwtf49af8/tiCHpfmjV+ks9FDIBQoKxuZz3r5eFLRbgWaX8pkvY0fZycFpUPw==,iv:H9PEEWacLZmsmNSTTJ/DQetl+M8Ul1SyiZJ9J3zNGjk=,tag:iXm+4ki0ifs5zVCztB2VLw==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:wwvbXS1ZcfU1,iv:0jU/WE3evbhjjC3JhGUX+lQ/FYGfSdMNAtGADofJxA4=,tag:kTEVjnWvhYh3EwhKRYZQUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UmplbUpsemhJVjRrcWVE
            RTNXWUoxeUM5U1pmbGxvQXpTUzZabkh1SjFNClA2U3NoRzl2U2N5UUIzak5vZWty
            eUJ2Q1p0UkhIVzV1MlJmaEh6MGR1MUkKLS0tIG1rMjZyc0N0Ry9raU4zSFptK1Rl
            YUxmbjNNTCtNQmp4VFYxQVlmOE9VK1EKx2mnQPLIenAJNcQKGdaNdhoHxkizNSjH
            ziRVKLouZpnOHuQER3arWeoziGp/R/h1v+d5ObMCu6rht+LbleK/6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T00:14:55Z"
    mac: ENC[AES256_GCM,data:6DT/CcrSw3PLIbRDh94lasJd7vBbqT+wlNplumm5tWrcvh+PDuQXr31jQNxhHPNP9AZUyMJHGZ05C0zkQwFmWA8Rhp/4LbDHYrJJERQHRdzxAduYdS4bdmvdD1AeiZr4QhczYwQZt2r8Y/j9mqte3POp2tu0/9lwAtx3+S0PzyQ=,iv:4hk3BVa2X+0I+HG1rdQ+T1c8rW/g8MAScylWISG31rE=,tag:xRDw/o44rQrNqT65TLHd4A==,type:str]
    version: 3.13.3
