---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: swing-thoughts-redirect
spec:
  redirectRegex:
    regex: ^https?://(?:www\.)?swingthoughtspro\.com(?:/.*)?$
    replacement: https://swingthoughtspro.com/support
    permanent: true
