---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: swing-thoughts-redirect
spec:
  redirectRegex:
    regex: ^https?://swingthoughts\.harville\.dev/?(.*)
    replacement: https://swing-thoughts.harville.dev/$1
    permanent: true
