---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - postgres.yaml
  - rabbitmq.yaml
  - embeddings.yaml
  - middleware.yaml
  - helmrelease.yaml
  - public.ingress.yaml
