---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Namespaces
  - ../../../infrastructure/base/namespaces
  # Helm
  - ../../../infrastructure/base/traefik
  - ../../../infrastructure/base/cert-manager
  - ../../../infrastructure/base/metallb
  - ../../../infrastructure/base/reflector
  - ../../../infrastructure/base/longhorn
  - ../../../infrastructure/base/monitoring
  - ./secrets/cert-manager/cloudflare-api-token.yaml
  - ./secrets/monitoring/cluster-user-auth.yaml
patches:
  - target:
      kind: Ingress
      namespace: longhorn-system
    patch: |-
      - op: add
        path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.entrypoints
        value: websecure
