---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: runway
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
  url: https://github.com/isaiah-harville/runway.git
