---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator-mcp
  namespace: flux-system
spec:
  interval: 30m
  dependsOn:
    - name: flux-operator
      namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 1
      remediateLastFailure: true
      strategy: rollback
  chartRef:
    kind: OCIRepository
    name: flux-operator-mcp
    namespace: flux-system
  values:
    transport: http
    readonly: true
    priorityClassName: system-cluster-critical
    networkPolicy:
      create: true
      ingress:
        namespaces:
          - flux-system
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi
