---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gitrepository.yaml
  - books.yaml
  - homepage.yaml
  - lmstack-router.yaml
  - nginx.yaml
  - pigeon-relay.yaml
  - automation.yaml
