apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:IK6nz28HIZIO94ONkZdfZIolQXuVz2PiyTiocLMW1Gv4Uc28k9nogg==,iv:4SRwcWUyBFW8LXYhFmLxfY70F2SkEzPvfGHCD4APtKg=,tag:hKRfB1g16ThJzU/lLajW2w==,type:str]
sops:
    age:
        - recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N0ZyR0VBdlZzTytyZC9H
            Vm1nUHNVaWMxbjJhSUxBZkRwWDcxUjlvMW44CkpBS2tYRjJuUi9uR3dWL3JrUmVM
            alpwWU9JZC9ZZk5GS1BZZEdPMDZjRjQKLS0tIFBvRm1xR0szRXZNNU5SeFFqY0RK
            SWRHbVBsVGNqbmx2a01kVEFNWFByR1kKnIpJxDl3wHOWAmNIJ2GJ2ejD2f2YDD9S
            qAFqPzmqL73PCOdz3kvvH+Z3gTkw3D16zTh98Bg21X8ihVJW7GP8MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T20:37:23Z"
    mac: ENC[AES256_GCM,data:hA0SAGdVl94UTNmqaBh0qmGk6NiPq3r3EhAmEN1w53OhIXwC4Jusns7UV3kk0uUG1sUj+sABrlrlD6rORq1/xR6RDvT+KCX186Zm5T0+MvrzQbZuSccyCaj8pn2Mm2t9vRovYt3Yos4InMvsk2k0v3xh4b9UtEdptzoVlLomur0=,iv:+yeOLLAFrG8/S03ETBDWwQeM9eGS1+Bu2GbOSE9wMrA=,tag:Z0rDvsJdxzTRsyEbnqUqEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
