---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - sources.kustomization.yaml
  - infra.kustomization.yaml
  - issuers.kustomization.yaml
  - apps-certificates.kustomization.yaml
  - metallb-config.kustomization.yaml
  - apps.kustomization.yaml
