---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: apps
data:
  bookmarks.yaml: |
    []
  kubernetes.yaml: |
    mode: cluster
    ingress: true
  services.yaml: |
    []
  settings.yaml: |
    title: Harville Homelab
    description: Internal dashboard for cluster services
  widgets.yaml: |
    - search:
        provider: duckduckgo
        target: _blank
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: homelab
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
