---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - helmrelease.yaml
  - local-path-storageclass.yaml
  - longhorn-retain.storageclass.yaml
  - longhorn-database.storageclass.yaml
  - longhorn-media.storageclass.yaml
  - recurring-jobs.yaml
  - backuptarget.yaml
  - offsite-labels.yaml
  - longhorn-r2.sops.yaml
  - ingress.yaml
configMapGenerator:
  - name: longhorn-offsite-labels
    files:
      - offsite_labels.py=scripts/offsite_labels.py
