apiVersion: v1
kind: Secret
metadata:
    name: switchback-site-secrets
    namespace: harville-labs
type: Opaque
stringData:
    #ENC[AES256_GCM,data:V8rnOfh+wYJGDYTY23k01d8D6FuDjkRIQ94jjN2wlpnhgYWHX0aUebMyejf0+NBn+lgonvnY0JiVNRS2eZkiT08iZn1xs2Av,iv:pHU68VsciHVb+Dox5QEcqbckRWkqMFCi9cVytSHO4Qs=,tag:KyW3Yd7Ge0SuzReYbVbTog==,type:comment]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:aoQMzD0zPucEfgnsmJD9ZaAK2E67H5dIHiXv0F+D0WroxVrSQkTIiAki11Gi2PTcwbA+66Rn45AWVg+i2CN6Cw==,iv:hpRSsFwqotIfSomUxmJE+QvA6jsCa3Sdb7UCOMC9b8Y=,tag:+sBb/N8pJOcGHnW7xXteIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZ1JzVG4rbncwdGYxVlVi
            V2xqOVFRZDRRTWJKSjJlVW1CRldwSGZlWVNNCmJyc0xLYS9mZHRoakFBenNoaVI3
            c3RKNjBVbjBkT0lnNlhVcjVidmZkTzQKLS0tIGNXaC9kL2pSbFg2Q0xkcGN2aHFu
            Mm1zRy8yNFlYQjVwMUFORlMrVHVhZXMK08DlBAPKXVKOJ+qVfIAE+isUhhz2IcP1
            eHxqa2HPOoJunwTAHe0bPkvp/qLXXI8e89AMXvpbIQixgPGJmEg/Xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ukgkhw204tv9u00mf57jfmxwkfhrp0f6k3vjak3caztelhgh5us9a5jj4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T16:36:02Z"
    mac: ENC[AES256_GCM,data:5OZ8HAHuYY4dCjcSGaNR2gtpOyyWNJp+4JT32E0sToX9oeoaJd6IgKCccdyBzr/kHCUSihqEshJ5pVN6b/7I/gpHARDy/u5A82GNJ7I6qJjWOuunXnKVgitfWU/9gRM8BbmYsFjSelybSyq8eYy7+7S9+U3nwe5q/W1tR1zdRTs=,iv:4mn41aYvUBl2yLxD+v8Vd/bqKWK1ibE6Ks/6Cih1MGo=,tag:dEmtEjTmhUPdcMoltCdG/A==,type:str]
    version: 3.13.3
