---
apiVersion: v1
kind: Service
metadata:
  name: vllm-router
  namespace: apps
  labels:
    app: vllm-router
spec:
  selector:
    app: vllm-router
  ports:
    - name: http
      port: 8001
      targetPort: 8001
