---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - omni-terraform.sops.yaml
  - github-config.sops.yaml
  - controller.helmrelease.yaml
  - runner-scale-set.helmrelease.yaml
  - terraform-rbac.yaml
