---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harville-wildcard
spec:
  secretName: harville-wildcard-shared-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "apps,monitoring,longhorn-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "apps,monitoring,longhorn-system"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns
  dnsNames:
    - "*.harville.dev"
    - "*.int.harville.dev"
