---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: apps
spec:
  interval: 30m
  releaseName: authelia
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 1
      remediateLastFailure: true
      strategy: rollback
  chart:
    spec:
      chart: authelia
      version: "0.10.49"
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system
  values:
    nameOverride: authelia
    pod:
      kind: StatefulSet
      replicas: 1
    ingress:
      enabled: false
    persistence:
      enabled: true
      existingClaim: authelia
    configMap:
      identity_validation:
        reset_password:
          secret:
            value: b65832c47cfbb4d1b397f13813067d656304fa7cc1579267846f0dd35d72f542
      key: configuration.yaml
      existingConfigMap: authelia-config
      filters:
        disabled: false
      session:
        encryption_key:
          value: 6a03e418e48b798386e23eaefc8d9fecd74cd9cea140a74c13e0a5742de728c6
      storage:
        encryption_key:
          value: f9a039b25f6729155a90d29481a9ad06a80c1cf838b1d9cb9b29546a6367db3c
    secret:
      mountPath: /secrets
      additionalSecrets:
        authelia-extras: {}
        authelia-oidc-rsa: {}
        authelia-secrets: {}
        authelia-users-database: {}
