---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openwebui
  namespace: apps
spec:
  interval: 30m
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: StatefulSet
              name: openwebui
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: WEBUI_URL
                  value: https://webui.harville.dev
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: ENABLE_OAUTH_SIGNUP
                  value: "true"
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
                  value: "true"
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: OAUTH_CLIENT_ID
                  value: open-webui
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: openwebui-oidc
                      key: OAUTH_CLIENT_SECRET
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: OPENID_PROVIDER_URL
                  value: https://auth.harville.dev/.well-known/openid-configuration
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: OAUTH_PROVIDER_NAME
                  value: Authelia
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: OAUTH_SCOPES
                  value: openid email profile groups
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: ENABLE_OAUTH_ROLE_MANAGEMENT
                  value: "true"
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: OAUTH_ALLOWED_ROLES
                  value: openwebui,openwebui-admin
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: OAUTH_ADMIN_ROLES
                  value: openwebui-admin
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: OAUTH_ROLES_CLAIM
                  value: groups
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: OAUTH_CODE_CHALLENGE_METHOD
                  value: S256
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 1
      remediateLastFailure: true
      strategy: rollback
  chart:
    spec:
      chart: open-webui
      version: "12.10.0"
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  values:
    fullnameOverride: openwebui
    ollama:
      enabled: true
      persistentVolume:
        enabled: true
        size: 50Gi
        accessModes:
          - ReadWriteOnce
    pipelines:
      enabled: false
    persistence:
      enabled: true
