---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-ollama-longhorn
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-ha
