---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    prometheus:
      prometheusSpec:
        retention: 24h
        storageSpec: null
    alertmanager:
      alertmanagerSpec:
        storage: {}
    grafana:
      adminPassword: "admin"
      persistence:
        enabled: true
        type: pvc
        size: 10Gi
        accessModes:
          - ReadWriteOnce
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: traefik-internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Observability
          gethomepage.dev/name: Grafana
          gethomepage.dev/description: Dashboards and alerting
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - grafana.int.harville.dev
        tls:
          - hosts:
              - grafana.int.harville.dev
            secretName: harville-wildcard-tls
